### PR TITLE
Use Perfect Forwarding in all functions that use `apply` family of functors

### LINKED ISSUE #3208: Undefined behavior in combination of apply_scalar_binary/make_holder/to_ref_if
This issue is to collect information from https://github.com/stan-dev/math/pull/3203 in one place.

Basic summary:

On GCC, since c71dd3e (#2642), both `./test/prob/poisson/poisson_ccdf_log_00000_generated_v_test` and `./test/prob/loglogistic/loglogistic_cdf_00001_generated_ffv_test` fail due to taking a reference to something on the stack. The first fails under normal optimization settings consistently, the second is sporadic but can be made consistent by compiling with ASAN.

ASAN specifically blames
https://github.com/stan-dev/math/blob/3a196d410415ee2cc56c0e51ec73a2e1970a08a4/stan/math/prim/prob/poisson_lccdf.hpp#L55-L57

and

https://github.com/stan-dev/math/blob/3a196d410415ee2cc56c0e51ec73a2e1970a08a4/stan/math/prim/prob/loglogistic_cdf.hpp#L116

as the problematic lines. 

The discussion in https://github.com/stan-dev/math/pull/2414#issuecomment-1853299106 seems relevant, as @bgoodri was running into segfaults with a similar line in `poisson_lcdf`. 

There are shockingly few places where we use to_ref_if on an expression which is the result of an apply_scalar_binary call, I believe it is only in:

stan/math/prim/prob/loglogistic_cdf.hpp
stan/math/prim/prob/loglogistic_lpdf.hpp
stan/math/prim/prob/pareto_type_2_lcdf.hpp
stan/math/prim/prob/poisson_cdf.hpp
stan/math/prim/prob/poisson_lccdf.hpp
stan/math/prim/prob/poisson_lcdf.hpp
stan/math/prim/prob/weibull_lpdf.hpp

@SteveBronder believes the correct fix is probably to make the `apply_scalar_` functions _and all callsites thereof_ into perfect forwarding templates. The other solution involves materializing a signficant number of copies which would have a performance impact

### PR DESCRIPTION
**Pull request by SteveBronder**
## Summary

This fixes #3208 by using perfect forwarding for all functions that use our underlying apply family of functions for calling functions on containers and containers and containers. The issue was that the `Holder` class, when used in the apply functors, did not have enough type information to know which arguments it should take ownership of. 

Consider the following function, where all types are passed in via constant reference.

```cpp
template <typename T1, typename T2, require_any_container_t<T1, T2>* = nullptr>
inline auto gamma_p(const T1& a, const T2& b) {
  return apply_scalar_binary(
      [](const auto& c, const auto& d) { return gamma_p(c, d); }, a, b);
}
```

Calling this function with an Eigen expression that has a temporary in it would not give `apply_scalar_binary` and the `Holder` inside of `apply_scalar_binary` enough information to know that the `Holder` class should own any of the input arguments. As an example we can look at a simplified version of the code used in `poisson_lccdf.hpp`.  
```cpp
auto log_Pi = log(gamma_p(n_val + 1.0, lambda_val)));
double log_sum = sum(log_Pi);
```
`gamma_p` uses `apply_scalar_binary` and `log` uses `apply_scalar_unary`. We need to make sure the inputs and results of the `gamma_p` function do not fall out of scope by the time we go through `log` and then assign to `log_Pi`. Before this PR it would be possible for the expression `n_val + 1.0` to fall out of scope as well as the result of `gamma_p` to go out of scope from `log` after `log_Pi` is assigned.

To combat this we now use perfect forwarding for all of the functions that use our internal `apply` family of functors. This should allow the `Holder` used internally by the apply functors to know which types need to be owned by it to make sure things do not fall out of scope.

## Tests

There is no new tests for this. Since it is an isue on gcc I do wonder how we should test this in our CI/CD?

## Side Effects

I'd like to think of some test we can write so that, in the future, developers do not accidentally write functions that use the apply family of functors that do not use perfect forwarding.

## Release notes

Adds perfect forwarding to all functions that use the apply family of functors.

## Checklist

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by WardBrian** [comment]
@SteveBronder anything I can do to help this over the line?

File: stan/math/prim/core/complex_base.hpp [hunk 1]
```diff
@@ -17,6 +17,7 @@ namespace math {
 template <typename ValueType>
 class complex_base {
  public:
+  auto __rep() const { return *this; }
```
Comment (WardBrian) [inline stan/math/prim/core/complex_base.hpp]: I can't figure out from searching what this would do

**Comment by SteveBronder** [comment]
Right now it is just making sure the tests pass. I think I got it so we should be good!

File: Jenkinsfile [hunk 2]
```diff
@@ -413,7 +413,8 @@ pipeline {
                         unstash 'MathSetup'
                         script {
                             sh "echo O=0 > make/local"
-                            sh "echo CXX=${CLANG_CXX} -Werror >> make/local"
+                            sh "echo CXX=${GCC} -Werror >> make/local"
+                            sh "echo CXXFLAGS+=-fsanitize=address >> make/local"
```
Comment (WardBrian) [inline Jenkinsfile]: If you intend to keep this we will want to study what it does to the overall test time. It looks like it is currently at 3x the normal time for this stage and counting.

If you _don't_ want to keep this and it's just a sanity check, you might also want to remove the `O=0` line above -- my understanding is sanitizers won't catch everything at -O0

**Review by WardBrian — COMMENTED** [review]
Gonna leave the proper review to @andrjohns, just two things that stood out

File: Jenkinsfile (hunk 2 above)
Comment (SteveBronder) [reply Jenkinsfile]: I just wanted to run this via jenkins to confirm this fixed the error. Let me set this to a higher optim level

**Comment by WardBrian** [comment]
Math pipeline looks good, upstream has some (I believe legitimate) failures. All seem to blame `trigamma` in some way or another

```

--- Compiling C++ code ---
clang++-6.0 -std=c++17 -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O0 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.87.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header.hpp.gch/model_header_4_2.hpp.gch -x c++ -o ../stanc3/test/integration/good/stanc_helper.o ../stanc3/test/integration/good/stanc_helper.hpp
In file included from ../stanc3/test/integration/good/int_overloads.hpp:1:
In file included from stan/src/stan/model/model_header.hpp:6:
In file included from /home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math.hpp:19:
In file included from /home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev.hpp:11:
In file included from /home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/constraint.hpp:24:
In file included from /home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/constraint.hpp:4:
In file included from /home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun.hpp:335:
/home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/trigamma.hpp:142:12: error: function 'trigamma<stan::math::var_value<double, void> &, nullptr>' with deduced return type cannot be used before it is defined
    return trigamma(std::forward<T>(x));
           ^
/home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/functor/apply_scalar_unary.hpp:34:15: note: in instantiation of function template specialization 'stan::math::trigamma_fun::fun<stan::math::var_value<double, void> &>' requested here
    return F::fun(std::forward<T2>(x));
              ^
/home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/trigamma.hpp:159:47: note: in instantiation of function template specialization 'stan::math::apply_scalar_unary<stan::math::trigamma_fun, stan::math::var_value<double, void> &, void>::apply<stan::math::var_value<double, void> &>' requested here
  return apply_scalar_unary<trigamma_fun, T>::apply(std::forward<T>(x));
                                              ^
../stanc3/test/integration/good/int_overloads.hpp:521:44: note: in instantiation of function template specialization 'stan::math::trigamma<stan::math::var_value<double, void> &, nullptr>' requested here
      transformed_param_real = stan::math::trigamma(p_real);
                                           ^
../stanc3/test/integration/good/int_overloads.hpp:811:12: note: in instantiation of function template specialization 'int_overloads_model_namespace::int_overloads_model::log_prob_impl<false, false, Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1>, Eigen::Matrix<int, -1, 1, 0, -1, 1>, nullptr, nullptr, nullptr>' requested here
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
           ^
/home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/src/stan/model/model_base_crtp.hpp:98:50: note: in instantiation of function template specialization 'int_overloads_model_namespace::int_overloads_model::log_prob<false, false, stan::math::var_value<double, void> >' requested here
    return static_cast<const M*>(this)->template log_prob<false, false>(theta,
                                                 ^
../stanc3/test/integration/good/int_overloads.hpp:129:3: note: in instantiation of member function 'stan::model::model_base_crtp<int_overloads_model_namespace::int_overloads_model>::log_prob' requested here
  ~int_overloads_model() {}
  ^
/home/jenkins/workspace/Stan_Stan_downstream_tests/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/trigamma.hpp:158:13: note: 'trigamma<stan::math::var_value<double, void> &, nullptr>' declared here
inline auto trigamma(T&& x) {
            ^
1 error generated.
make: [make/program:77: ../stanc3/test/integration/good/int_overloads.o] Error 1 (ignored)
```

**Comment by SteveBronder** [comment]
Yes I missed one `requires` in `trigamma`

**Comment by WardBrian** [comment]
It looks like `inv_gamma_00000_generated_vv_test` and `chi_square_00000_generated_v_test` are both failing to build

**Comment by SteveBronder** [comment]
Yes it looks like there was a conflict with some code using `using boost::math::lgamma`. We shouldn't have those anyway so I'm going to remove them.

**Comment by WardBrian** [comment]
@andrjohns are you still up for reviewing?

File: stan/math/prim/core/complex_base.hpp (hunk 1 above)
Comment (SteveBronder) [reply stan/math/prim/core/complex_base.hpp]: Our `complex<var>` and `complex<fvar<T>>` impls still call std library functions sometimes. In those functions, at least for gcc, sometimes they request this `__rep()` function. The `__rep()` in their code just returns a copy of `this` like the one here. 

But let me double check if this is still needed

**Comment by andrjohns** [comment]
> @andrjohns are you still up for reviewing?

Yep still all good! @SteveBronder should I do a first pass or do you have more changes?

**Comment by SteveBronder** [comment]
I have just a little fix I need to make for the constraints but am afk ATM. Everything else is ready for review!

File: stan/math/prim/constraint/positive_constrain.hpp [hunk 3]
```diff
@@ -41,9 +41,10 @@ inline auto positive_constrain(const T& x) {
  * @return positive constrained version of unconstrained value(s)
  */
 template <typename T, typename S>
-inline auto positive_constrain(const T& x, S& lp) {
-  lp += sum(x);
-  return exp(x);
+inline auto positive_constrain(T&& x, S& lp) {
+  auto&& x_ref = to_ref(std::forward<T>(x));
+  lp += sum(x_ref);
+  return exp(std::forward<decltype(x_ref)>(x));
```
Comment (andrjohns) [inline stan/math/prim/constraint/positive_constrain.hpp]:
```suggestion
  return exp(std::forward<decltype(x_ref)>(x_ref));
```

File: stan/math/prim/fun/abs.hpp [hunk 4]
```diff
@@ -49,8 +49,12 @@ inline auto abs(T x) {
  */
 struct abs_fun {
   template <typename T>
-  static inline auto fun(const T& x) {
-    return abs(x);
+  static inline auto fun(T&& x) {
+    if constexpr (std::is_arithmetic_v<std::decay_t<T>>) {
+      return std::abs(x);
+    } else {
```
Comment (andrjohns) [inline stan/math/prim/fun/abs.hpp]: Is this necessary or just a testing thing? The earlier scalar overload should capture the arithmetic case right?

File: stan/math/prim/fun/fabs.hpp [hunk 5]
```diff
@@ -62,9 +68,9 @@ inline auto fabs(const Container& x) {
  */
 template <typename Container,
           require_container_st<std::is_arithmetic, Container>* = nullptr>
-inline auto fabs(const Container& x) {
+inline auto fabs(Container&& x) {
   return apply_vector_unary<Container>::apply(
-      x, [](const auto& v) { return v.array().abs(); });
+      std::forward<Container>(x), [](auto&& v) { return v.array().abs(); });
```
Comment (andrjohns) [inline stan/math/prim/fun/fabs.hpp:69]: The PR is a bit inconsistent on whether the `apply_vector_unary` functor should be `(auto&& v)` or `(const auto& v)`, can you standardise on one?

File: stan/math/prim/fun/inc_beta.hpp [hunk 6]
```diff
@@ -44,10 +44,10 @@ inline double inc_beta(double a, double b, double x) {
 template <typename T1, typename T2, typename T3,
           require_any_container_t<T1, T2, T3>* = nullptr,
           require_all_not_var_matrix_t<T1, T2, T3>* = nullptr>
-inline auto inc_beta(const T1& a, const T2& b, const T3& c) {
-  return apply_scalar_ternary([](const auto& d, const auto& e,
-                                 const auto& f) { return inc_beta(d, e, f); },
-                              a, b, c);
+inline auto inc_beta(T1&& a, T2&& b, T3&& c) {
+  return apply_scalar_ternary(
+      [](auto&& d, auto&& e, auto&& f) { return inc_beta(d, e, f); },
```
Comment (andrjohns) [inline stan/math/prim/fun/inc_beta.hpp]: Should the functor also be forwarding the `d, e, f` arguments to `inc_beta` as well?

File: stan/math/prim/fun/inv_inc_beta.hpp [hunk 7]
```diff
@@ -46,12 +46,10 @@ inline double inv_inc_beta(double a, double b, double p) {
...
 template <typename T1, typename T2, typename T3,
           require_any_container_t<T1, T2, T3>* = nullptr>
-inline auto inv_inc_beta(const T1& a, const T2& b, const T3& c) {
+inline auto inv_inc_beta(T1&& a, T2&& b, T3&& c) {
   return apply_scalar_ternary(
-      [](const auto& d, const auto& e, const auto& f) {
-        return inv_inc_beta(d, e, f);
-      },
-      a, b, c);
+      [](auto&& d, auto&& e, auto&& f) { return inv_inc_beta(d, e, f); },
```
Comment (andrjohns) [inline stan/math/prim/fun/inv_inc_beta.hpp]: Same query around forwarding the inner arguments here

File: stan/math/prim/fun/inv_logit.hpp [hunk 8]
```diff
@@ -48,15 +48,13 @@ namespace math {
...
  * @return Inverse logit of argument.
  */
-inline double inv_logit(double a) {
+template <typename T, require_arithmetic_t<T>* = nullptr>
+inline double inv_logit(T&& a) {
   if (a < 0) {
     double exp_a = std::exp(a);
-    if (a < LOG_EPSILON) {
-      return exp_a;
-    }
```
Comment (andrjohns) [inline stan/math/prim/fun/inv_logit.hpp]: This shouldn't be dropped imo, change is unrelated to the PR (and saves some operations)

File: stan/math/prim/fun/log1m_inv_logit.hpp [hunk 9]
```diff
@@ -30,28 +30,19 @@ namespace math {
...
- * @param u argument
+ * @tparam T An arithmetic type.
+ * @param uu argument
  * @return log of one minus the inverse logit of the argument
  */
-inline double log1m_inv_logit(double u) {
-  using std::exp;
+template <typename T, require_arithmetic_t<T>* = nullptr>
+inline double log1m_inv_logit(T&& uu) {
+  const auto u = static_cast<double>(uu);
```
Comment (andrjohns) [inline stan/math/prim/fun/log1m_inv_logit.hpp:39]: Why does this need the static cast?

File: stan/math/prim/fun/norm1.hpp [hunk 10]
```diff
@@ -12,28 +12,31 @@ namespace math {
...
  * @return L1 norm of v.
  */
-template <typename T, require_eigen_vt<std::is_arithmetic, T>* = nullptr>
-inline double norm1(const T& v) {
-  ref_type_t<T> v_ref = v;
-  return v_ref.template lpNorm<1>();
+template <typename Container,
+          require_eigen_vt<std::is_arithmetic, Container>* = nullptr>
+inline double norm1(Container&& x) {
+  ref_type_t<Container> x_ref = x;
```
Comment (andrjohns) [inline stan/math/prim/fun/norm1.hpp]:
```suggestion
  ref_type_t<Container> x_ref = std::forward<Container>(x);
```

File: stan/math/prim/fun/norm2.hpp [hunk 11]
```diff
@@ -12,28 +12,31 @@ namespace math {
...
+ * @return L2 norm of x.
  */
-template <typename T, require_eigen_vt<std::is_arithmetic, T>* = nullptr>
-inline double norm2(const T& v) {
-  ref_type_t<T> v_ref = v;
-  return v_ref.template lpNorm<2>();
+template <typename Container,
+          require_eigen_vt<std::is_arithmetic, Container>* = nullptr>
+inline double norm2(Container&& x) {
+  ref_type_t<Container> x_ref = x;
```
Comment (andrjohns) [inline stan/math/prim/fun/norm2.hpp]:
```suggestion
  ref_type_t<Container> x_ref = std::forward<Container>(x);
```

File: stan/math/prim/fun/rank.hpp [hunk 12]
```diff
@@ -17,14 +17,15 @@ namespace math {
...
 template <typename C, require_container_t<C>* = nullptr>
-inline int rank(const C& v, int s) {
+inline int rank(C&& v, int s) {
   check_range("rank", "v", v.size(), s);
   --s;  // adjust for indexing by one
-  return apply_vector_unary<C>::reduce(v, [s](const auto& vec) {
-    const auto& vec_ref = to_ref(vec);
+  return apply_vector_unary<C>::reduce(
+      std::forward<C>(v), [s](const auto& vec) {
+        const auto& vec_ref = to_ref(vec);
```
Comment (andrjohns) [inline stan/math/prim/fun/rank.hpp]:
```suggestion
      std::forward<C>(v), [s](auto&& vec) {
        auto&& vec_ref = to_ref(std::forward<decltype(vec)>(vec));
```

File: stan/math/prim/fun/sd.hpp [hunk 13]
```diff
@@ -23,10 +23,10 @@ namespace math {
  */
 template <typename T, require_container_t<T>* = nullptr,
           require_not_st_var<T>* = nullptr>
-inline auto sd(const T& m) {
+inline auto sd(T&& m) {
   using std::sqrt;
 
-  return apply_vector_unary<T>::reduce(m, [](const auto& x) {
+  return apply_vector_unary<T>::reduce(std::forward<T>(m), [](const auto& x) {
```
Comment (andrjohns) [inline stan/math/prim/fun/sd.hpp]:
```suggestion
  return apply_vector_unary<T>::reduce(std::forward<T>(m), [](auto&& x) {
```

Then can forward to `variance()` below

File: stan/math/prim/functor/apply_scalar_ternary.hpp [hunk 14]
```diff
@@ -93,8 +93,7 @@ inline auto apply_scalar_ternary(F&& f, T1&& x, T2&& y, T3&& z) {
  */
 template <typename F, typename T1, typename T2, typename T3,
           require_all_std_vector_vt<is_stan_scalar, T1, T2, T3>* = nullptr>
-inline auto apply_scalar_ternary(const F& f, const T1& x, const T2& y,
-                                 const T3& z) {
+inline auto apply_scalar_ternary(F&& f, T1&& x, T2&& y, T3&& z) {
   check_matching_sizes("Ternary function", "x", x, "y", y);
   check_matching_sizes("Ternary function", "y", y, "z", z);
   decltype(auto) x_vec = as_column_vector_or_scalar(x);
```
Comment (andrjohns) [inline stan/math/prim/functor/apply_scalar_ternary.hpp]: These should also be forwarding (like the corresponding `apply_scalar_binary` implementation), I'm guessing?

File: stan/math/prim/functor/apply_scalar_unary.hpp [hunk 15]
```diff
@@ -58,18 +58,23 @@ struct apply_scalar_unary<F, T, require_eigen_t<T>> {
...
-  static inline auto apply(const std::decay_t<T>& x) {
-    return x.unaryExpr([](auto&& x) {
-      return apply_scalar_unary<F, std::decay_t<decltype(x)>>::apply(x);
-    });
+  template <typename TT>
+  static inline auto apply(TT&& x) {
+    return make_holder(
+        [](auto&& xx) {
+          return std::forward<decltype(xx)>(xx).unaryExpr([](auto&& xxx) {
+            return apply_scalar_unary<F, decltype(xxx)>::apply(xxx);
```
Comment (andrjohns) [inline stan/math/prim/functor/apply_scalar_unary.hpp]:
```suggestion
            return apply_scalar_unary<F, decltype(xxx)>::apply(std::forward<decltype(xxx)>(xxx));
```

File: stan/math/prim/functor/apply_vector_unary.hpp [hunk 16]
```diff
@@ -191,7 +205,7 @@ struct apply_vector_unary<
         = plain_type_t<decltype(apply_vector_unary<T_vt>::apply(x[0], f))>;
     std::vector<T_return> result(x.size());
     std::transform(x.begin(), x.end(), result.begin(), [&f](auto&& xx) {
-      return apply_vector_unary<T_vt>::apply_no_holder(xx, f);
+      return apply_vector_unary<T_vt>::apply(xx, f);
```
Comment (andrjohns) [inline stan/math/prim/functor/apply_vector_unary.hpp:208]:
```suggestion
      return apply_vector_unary<T_vt>::apply(std::forward<decltype(xx)>(xx), f);
```

File: stan/math/prim/functor/apply_vector_unary.hpp [hunk 17]
```diff
@@ -67,14 +78,14 @@ struct apply_vector_unary<T, require_eigen_t<T>> {
    */
   template <typename F, typename T2 = T,
             require_t<is_eigen_matrix_base<plain_type_t<T2>>>* = nullptr>
-  static inline auto apply_no_holder(const T& x, const F& f) {
-    return f(x).matrix().derived();
+  static inline auto apply_no_holder(T2& x, F&& f) {
+    return std::forward<F>(f)(std::forward<T2>(x));
```
Comment (andrjohns) [inline stan/math/prim/functor/apply_vector_unary.hpp:82]: This is no longer returning the plain type now that the `.derived()` call is removed, should this at least be evaluating first since `make_holder` isn't used?

File: stan/math/prim/meta/holder.hpp [hunk 18]
```diff
@@ -362,9 +431,8 @@ inline auto make_holder_impl(F&& func, std::index_sequence<Is...>,
  * @param args arguments for the functor
  * @return `holder` referencing expression constructed by given functor
  */
-template <
-    typename F, typename... Args,
-    require_not_plain_type_t<std::invoke_result_t<F, Args&&...>>* = nullptr>
+template <typename F, typename... Args,
+          require_not_plain_type_t<std::invoke_result_t<F, Args&&...>>*>
```
Comment (andrjohns) [inline stan/math/prim/meta/holder.hpp:436]: Are these still well-formed without the `nullptr` default?

File: stan/math/rev/fun/norm1.hpp [hunk 19]
```diff
@@ -15,17 +15,18 @@ namespace math {
...
  */
-template <typename T, require_eigen_vector_vt<is_var, T>* = nullptr>
-inline var norm1(const T& v) {
-  arena_t<T> arena_v = v;
-  var res = norm1(arena_v.val());
-  reverse_pass_callback([res, arena_v]() mutable {
-    arena_v.adj().array() += res.adj() * sign(arena_v.val().array());
+template <typename Container,
+          require_eigen_vector_vt<is_var, Container>* = nullptr>
+inline var norm1(const Container& x) {
```
Comment (andrjohns) [inline stan/math/rev/fun/norm1.hpp]: Both the `norm1` and `norm2` here have been updated but are still passing by const ref

File: test/unit/math/mix/fun/ub_constrain_test.cpp [hunk 20]
```diff
@@ -119,9 +119,9 @@ TEST(mathMixMatFun, ub_stdvec_constrain_inf) {
 // matrix[], real
 TEST(mathMixMatFun, ub_stdvec_mat_mat_constrain) {
   Eigen::MatrixXd A_inner(2, 3);
-  A_inner << 5.0, 2.0, 4.0, -2.0, 0.0, 0.005;
+  A_inner << 5.0, 2.0, 4.0, -2.0, 1.0, 2.0;
```
Comment (andrjohns) [inline test/unit/math/mix/fun/ub_constrain_test.cpp:122]: Do these values need to be changed for the test to pass?

**Review by andrjohns — DISMISSED** [review]
A bunch of minor requests/queries, the main thing I'm not too sure about is the new specification for the `apply_scalar_unary` functions (with the `is_arithmetic_v<>` conditional) - what's necessitating that?

File: stan/math/prim/fun/norm1.hpp (hunk 10 above)
Comment (SteveBronder) [reply stan/math/prim/fun/norm1.hpp]: Actually this can just be `x.template lpNorm<1>();` since the type returned is a double so we just evaluate all the expressions here before returning.

File: stan/math/prim/functor/apply_vector_unary.hpp (hunk 16 above)
Comment (SteveBronder) [reply stan/math/prim/functor/apply_vector_unary.hpp:208]: std transform does not know whether `x` is a temporary so it will never do forwarding here.

File: stan/math/prim/functor/apply_vector_unary.hpp (hunk 17 above)
Comment (SteveBronder) [reply stan/math/prim/functor/apply_vector_unary.hpp:82]: Is there anywhere these functions are being used now?

File: stan/math/prim/meta/holder.hpp (hunk 18 above)
Comment (SteveBronder) [reply stan/math/prim/meta/holder.hpp:436]: These functions are forward declared at the top of the file. There we set the default of nullptr

File: test/unit/math/mix/fun/ub_constrain_test.cpp (hunk 20 above)
Comment (SteveBronder) [reply test/unit/math/mix/fun/ub_constrain_test.cpp:122]: On my desktop machine I was getting weird floating point errors when the values were small. But on my mac I did not get any fp errors. But these tests were failing on my desktop computer before this PR.

File: stan/math/prim/fun/abs.hpp (hunk 4 above)
Comment (SteveBronder) [reply stan/math/prim/fun/abs.hpp]: Yes I think I can remove these

File: stan/math/prim/fun/fabs.hpp (hunk 5 above)
Comment (SteveBronder) [reply stan/math/prim/fun/fabs.hpp:69]: Just fixed all these up

File: stan/math/prim/fun/inc_beta.hpp (hunk 6 above)
Comment (SteveBronder) [reply stan/math/prim/fun/inc_beta.hpp]: Yes good catch

File: stan/math/prim/fun/inv_inc_beta.hpp (hunk 7 above)
Comment (SteveBronder) [reply stan/math/prim/fun/inv_inc_beta.hpp]: 👍

File: stan/math/prim/fun/inv_logit.hpp (hunk 8 above)
Comment (SteveBronder) [reply stan/math/prim/fun/inv_logit.hpp]: 👍

File: stan/math/prim/fun/log1m_inv_logit.hpp (hunk 9 above)
Comment (SteveBronder) [reply stan/math/prim/fun/log1m_inv_logit.hpp:39]: T here can be an integer type

File: stan/math/prim/fun/sd.hpp (hunk 13 above)
Comment (SteveBronder) [reply stan/math/prim/fun/sd.hpp]: 👍

File: stan/math/prim/functor/apply_scalar_ternary.hpp (hunk 14 above)
Comment (SteveBronder) [reply stan/math/prim/functor/apply_scalar_ternary.hpp]: 👍

File: stan/math/prim/functor/apply_scalar_unary.hpp (hunk 15 above)
Comment (SteveBronder) [reply stan/math/prim/functor/apply_scalar_unary.hpp]: 👍

File: stan/math/rev/fun/norm1.hpp (hunk 19 above)
Comment (SteveBronder) [reply stan/math/rev/fun/norm1.hpp]: 👍

**Comment by WardBrian** [comment]
test/prob/beta_neg_binomial/beta_neg_binomial_cdf_00000_generated_vv_test segfaulted on the latest run it looks like

**Comment by WardBrian** [comment]
I'm running the distribution tests on this branch with all the tests enabled + `-O3` + ASan [here](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/PR-3221/49/pipeline). It is almost done, and so far looks good

**Comment by WardBrian** [comment]
Looks like that full run passed 👍🏻 

@andrjohns are you able to review again? Thanks!

File: stan/math/prim/functor/apply_scalar_ternary.hpp [hunk 21]
```diff
@@ -93,17 +93,19 @@ inline auto apply_scalar_ternary(F&& f, T1&& x, T2&& y, T3&& z) {
...
   check_matching_sizes("Ternary function", "x", x, "y", y);
   check_matching_sizes("Ternary function", "y", y, "z", z);
-  decltype(auto) x_vec = as_column_vector_or_scalar(x);
-  decltype(auto) y_vec = as_column_vector_or_scalar(y);
-  decltype(auto) z_vec = as_column_vector_or_scalar(z);
+  decltype(auto) x_vec = as_column_vector_or_scalar(std::forward<T1>(x));
+  decltype(auto) y_vec = as_column_vector_or_scalar(std::forward<T2>(y));
+  decltype(auto) z_vec = as_column_vector_or_scalar(std::forward<T3>(z));
   using T_return = std::decay_t<decltype(f(x[0], y[0], z[0]))>;
   std::vector<T_return> result(x.size());
```
Comment (WardBrian) [inline stan/math/prim/functor/apply_scalar_ternary.hpp]: We shouldn't be reading the size of a possibly-moved-from `x`, as it is unspecified what this would be. Moving this up a few lines should void any trouble

File: stan/math/prim/functor/apply_scalar_binary.hpp [hunk 22]
```diff
@@ -253,14 +261,14 @@ inline auto apply_scalar_binary(F&& f, T1&& x, T2&& y) {
...
           require_all_std_vector_vt<is_stan_scalar, T1, T2>* = nullptr>
-inline auto apply_scalar_binary(const F& f, const T1& x, const T2& y) {
+inline auto apply_scalar_binary(F&& f, T1&& x, T2&& y) {
   check_matching_sizes("Binary function", "x", x, "y", y);
-  decltype(auto) x_vec = as_column_vector_or_scalar(x);
-  decltype(auto) y_vec = as_column_vector_or_scalar(y);
+  decltype(auto) x_vec = as_column_vector_or_scalar(std::forward<T1>(x));
+  decltype(auto) y_vec = as_column_vector_or_scalar(std::forward<T2>(y));
   using T_return = std::decay_t<decltype(f(x[0], y[0]))>;
   std::vector<T_return> result(x.size());
```
Comment (WardBrian) [inline stan/math/prim/functor/apply_scalar_binary.hpp]: Same concern about moved-from `x`

File: stan/math/rev/fun/logit.hpp [hunk 23]
```diff
@@ -16,8 +16,8 @@ namespace math {
  * @param u The variable.
  * @return log odds of argument
  */
-template <typename T, require_stan_scalar_or_eigen_t<T>* = nullptr>
-inline auto logit(const var_value<T>& u) {
+template <typename T, require_var_t<T>* = nullptr>
+inline auto logit(T&& u) {
```
Comment (WardBrian) [inline stan/math/rev/fun/logit.hpp:20]: If the body of the function didn't change at all, does this actually do anything? Several of the rev files had similar changes

**Review by WardBrian — COMMENTED** [review]
I went through all of @andrjohns comments to confirm they were addressed, and a few other small things stood out to me

File: stan/math/prim/functor/apply_scalar_ternary.hpp (hunk 21 above)
Comment (SteveBronder) [reply stan/math/prim/functor/apply_scalar_ternary.hpp]: Good catch. I'll look for this elsewhere

File: stan/math/rev/fun/logit.hpp (hunk 23 above)
Comment (SteveBronder) [reply stan/math/rev/fun/logit.hpp:20]: Yes this avoids argument dependent lookup and instead relies on sfinae to decide which function to call. It helps stop accidental promotion to a var type

Comment (WardBrian) [reply stan/math/rev/fun/logit.hpp:20]: Ah, that makes sense. Thanks!

File: stan/math/prim/functor/apply_scalar_binary.hpp (hunk 22 above)
Comment (WardBrian) [reply stan/math/prim/functor/apply_scalar_binary.hpp]: @SteveBronder this one was still present in the latest push

Comment (SteveBronder) [reply stan/math/prim/functor/apply_scalar_binary.hpp]: Yes I'm going through all the files that use forward to make sure I get all of them at once

Comment (WardBrian) [reply stan/math/prim/functor/apply_scalar_binary.hpp]: Do you think we could use https://clang.llvm.org/extra/clang-tidy/checks/bugprone/use-after-move.html?

Comment (WardBrian) [reply stan/math/prim/functor/apply_scalar_binary.hpp]: It looks like clang-tidy up to at least version 18 is not that good at diagnosing `forward` with that lint. It seems to work on trunk in godbolt, but not locally. Too bad

**Review by WardBrian — DISMISSED** [review]
Just gave this a once over and it looks good to me now. We can wait a couple days before merging if you want to give @andrjohns another chance to look

**Review by WardBrian — APPROVED** [review]

**Comment by WardBrian** [comment]
@SteveBronder it looks like a few of the SoA signatures aren't compiling any more:
https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/PR-1527/7/pipeline

```
'../test/integration/good/function-signatures/math/matrix/trigamma.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/trunc.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/bessel_second_kind.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/round.stan' had fails '[]' and errors '['Did not compile!']'
```

All of the errors are `error: no matching function for call to 'NAME'`, except for the bessel second kind, which is
```
In file included from ../../test/integration/good/function-signatures/math/matrix/bessel_second_kind.hpp:1:
In file included from stan/src/stan/model/model_header.hpp:6:
In file included from /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math.hpp:19:
In file included from /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev.hpp:11:
In file included from /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/constraint.hpp:24:
In file included from /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/constraint.hpp:4:
In file included from /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun.hpp:32:
/home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/bessel_second_kind.hpp:59:16: error: function 'bessel_second_kind<const std::vector<int, std::allocator<int> > &, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void>, nullptr>' with deduced return type cannot be used before it is defined
        return bessel_second_kind(std::forward<decltype(c)>(c),
               ^
/home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/functor/apply_scalar_binary.hpp:53:10: note: in instantiation of function template specialization 'stan::math::bessel_second_kind(const std::vector<int, std::allocator<int> > &&, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void> &&)::(anonymous class)::operator()<const std::vector<int, std::allocator<int> > &, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void> >' requested here
  return std::forward<F>(f)(std::forward<T1>(x), std::forward<T2>(y));
         ^
/home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/bessel_second_kind.hpp:57:10: note: in instantiation of function template specialization 'stan::math::apply_scalar_binary<(lambda at /home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/bessel_second_kind.hpp:58:7), const std::vector<int, std::allocator<int> > &, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void>, nullptr, nullptr>' requested here
  return apply_scalar_binary(
         ^
../../test/integration/good/function-signatures/math/matrix/bessel_second_kind.hpp:1798:21: note: in instantiation of function template specialization 'stan::math::bessel_second_kind<const std::vector<int, std::allocator<int> > &, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void>, nullptr>' requested here
        stan::math::bessel_second_kind(d_int_array,
                    ^
/home/jenkins/workspace/Stan_Stanc3_PR-1527@2/compile-good-O1/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/bessel_second_kind.hpp:56:13: note: 'bessel_second_kind<const std::vector<int, std::allocator<int> > &, stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void>, nullptr>' declared here
inline auto bessel_second_kind(T1&& a, T2&& b) {
```

**Comment by WardBrian** [comment]
I'm guessing it is because the rev specializations of those functions hardcode `var` or `var_value` rather than using template traits

**Comment by WardBrian** [comment]
Jenkins also failed during the merge in this repo:
https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/develop/357/pipeline

**Comment by WardBrian** [comment]
@SteveBronder do you have a sense of how easy this would be to fix?

If it ends up being complicated I would advocate for reverting this and leaving math as-is in the release, for the sake of getting all the other bugfixes in the last 8 months in the hands of users

**Comment by SteveBronder** [comment]
```
'../test/integration/good/function-signatures/math/matrix/trigamma.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/trunc.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/bessel_second_kind.stan' had fails '[]' and errors '['Did not compile!']'
'../test/integration/good/function-signatures/math/matrix/round.stan' had fails '[]' and errors '['Did not compile!']'
```

I'm looking at these functions and idt `trigamma`, `trunc`, and `round` should have worked for SoA matrices in the first place. Like looking at `trigamma` they all use `trigama_impl` which is only made for scalar types. And `round` and `trunc` do not have SoA specializations either. So I think in the compiler we should turn those ones off.

The Bessel function one I think is a real error from ADL since the perfect forwarding function is being chosen over the others. I can open up a PR for that one rn

**Comment by WardBrian** [comment]
> I'm looking at these functions and idt `trigamma`, `trunc`, and `round` should have worked for SoA matrices in the first place.

Are you sure? They've been marked as SoA supported since the first compiler pr https://github.com/stan-dev/stanc3/pull/955.
Why have they been compiling until now?
