### PR TITLE
Bugfix/issue 1100 missing bounds

### LINKED ISSUE #1100: Missing bounds checks in some lpdfs
## Description

multi_normal_lpdf, multi_normal_cholesky_lpd, multi_normal_prec_lpdf, and multi_student_t_lpdf do not do proper error checking, causing segfaults.

Fix in PR once I have a bug number to reference.

## Example
This crashes R:

```
library(rstan)

model_code <- '
data {
  vector[4] y[3];
}
parameters{
  vector[4] mu[4];
  cov_matrix[4] sigma;
}
model {
  y ~ multi_normal(mu, sigma);
}
'

data = list(y=list(c(0, 1, 2, 3), c(0, 1, 2, 3), c(0, 1, 2, 3)))

fit <- stan(model_code = model_code, data=data)
```

```
peter@gtower:~/stan/math$ R -f test_stan.r 

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
[...]
> library(rstan)
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.18.2, GitRev: 2e1f913d3ca3)
[...]
> fit <- stan(model_code = model_code, data=data)

SAMPLING FOR MODEL 'b7dddee2f8557c3ad231857773291561' NOW (CHAIN 1).
Segmentation fault (core dumped)
```

## Expected Output
These functions should throw invalid_argument exceptions instead of causing segmentation faults.

#### Current Version:
rstan (Version 2.18.2, GitRev: 2e1f913d3ca3)

(The PR adds unit tests to the math library that cause segfaults on the current HEAD of develop. 6258515e1cc3e659d38f633841959d9a93e2c0ab.)

### PR DESCRIPTION
**Pull request by peterwicksstringfield**
## Summary

Add tests and fix lpdfs to close #1100.

## Tests

test/unit/math/prim/mat/prob/multi_normal_test.cpp
test/unit/math/prim/mat/prob/multi_normal_cholesky_test.cpp
test/unit/math/prim/mat/prob/multi_normal_prec_test.cpp
test/unit/math/prim/mat/prob/multi_student_t.cpp

## Side Effects

None.

## Checklist

- [X] Math issue #1100
- [X] Copyright holder: Peter Wicks Stringfield
    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
- [X] the basic tests are passing
- [X the code is written in idiomatic C++ and changes are documented in the doxygen
- [X] the new changes are tested

### CODE REVIEW

**Comment by syclik** [comment]
@peterwicksstringfield, thank you for submitting the PR!

Question: does your new test show the behavior of the bug? I ran the tests on `develop` and it ran fine. (I might have done that wrong; hopefully that's the case.)

File: stan/math/prim/mat/prob/multi_normal_lpdf.hpp [hunk 1]
```diff
@@ -37,6 +38,15 @@ typename return_type<T_y, T_loc, T_covar>::type multi_normal_lpdf(
   check_ldlt_factor(function, "LDLT_Factor of covariance parameter",
                     ldlt_Sigma);
 
+  size_t number_of_y = length_mvt(y);
+  size_t number_of_mu = length_mvt(mu);
+  if (number_of_y == 0 || number_of_mu == 0)
+    return 0.0;
+  if (number_of_y > 1 && number_of_mu > 1)
+    check_size_match(function, "Number of vectors of the random variable",
```
Comment (syclik) [inline stan/math/prim/mat/prob/multi_normal_lpdf.hpp]: Mind explaining the logic here? Either one of `y` or `mu` has to have two or more elements? 

Is this because `length_mvt()` will return 1 for a single vector?

Wouldn't the sizes be wrong if `y` is legitimately a vector of vectors of length 1 and `mu` is a vector of vectors that's larger?

**Comment by bob-carpenter** [comment]
> @syclik commented on this pull request.
> 
> In stan/math/prim/mat/prob/multi_normal_lpdf.hpp:
> 
> ...

> +  if (number_of_y > 1 && number_of_mu > 1)
> +    check_size_match(function, "Number of vectors of the random variable",
> 
...

> Wouldn't the sizes be wrong if y is legitimately a vector of vectors of length 1 and mu is a vector of vectors that's larger?

Daniel's right---we don't want to allow vectors of length 1 to mix with vectors of other sizes.

File: stan/math/prim/mat/prob/multi_normal_lpdf.hpp (hunk 1 above)
Comment (peterwicksstringfield) [reply stan/math/prim/mat/prob/multi_normal_lpdf.hpp]: @syclik 

You are correct. The special case is necessary in order to distinguish eigen::vector(1, 2, 3) which should be able to mix with ("is conformable with"?) std::vector(eigen::vector(1, 1, 1), ...). But as it was first written it incorrectly also allows std::vector(eigen::vector(1, 2, 3)) to mix with std::vector(eigen::vector(1, 1, 1), ...).

So really, I need something like:

"contains_vectors" or

```
is_vector<typename std::remove_reference<decltype(x[0])>::type>::value;
```

I've made the necessary changes.

However the upstream tests failed and stopped the build. Can someone take a look?

Comment (syclik) [reply stan/math/prim/mat/prob/multi_normal_lpdf.hpp]: @peterwicksstringfield, I'm really sorry -- I missed this notification. It looks like you've gotten it fixed. I'll take a look.

**Comment by syclik** [comment]
I also verified that the actual Stan program that showed the bug can sample with this fix.

**Comment by syclik** [comment]
(and I also verified that it correctly kicks out when there's an array of length 1 of a vector that matches in size!)
