### PR TITLE
fix threading for clang, fixes #844

### LINKED ISSUE #844: threading broken under clang
#### Summary:
Under clang the threading is broken in develop.

#### Description:
A segfault is triggered.

#### Reproducible Steps:
Turn on threading and run the test `test/unit/math/rev/mat/functor/gradient_test.cpp`... it fails.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
It should just work as before.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

### PR DESCRIPTION
**Pull request by wds15**
#### Submission Checklist

- [ ] Run unit tests: `./runTests.py test/unit`
- [X] Run cpplint: `make cpplint`
- [X] Declare copyright holder and open-source license: see below

#### Summary:
clang + threading is broken right now. This PR adds testing on travis with clang and threading along with the fixes to the AD stack to make it work again. To see things failing, please use `develop` for this.

```
[21:01:42][sebi@sebastians-macbook-pro-1:~/work/performance-tests-cmdstan]$ ./comparePerformance.py performance.csv develop_performance.csv
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 0.99)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 1.04)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 1.03)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 0.98)
('compilation', 1.09)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 0.99)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 0.94)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 0.99)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 0.97)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 0.96)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 1.38)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 0.89)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 1.04)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 1.04)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 0.92)
```

#### Intended Effect:
Add test coverage for clang+threading and fix it.

#### How to Verify:
1. enable threading with `CXXFLAGS+=-DSTAN_THREADS` in your `make/local`
2. use `CC=clang++`
3. you can confirm that this is broken on `develop` and works on this branch by running the test `test/unit/math/rev/mat/functor/gradient_test.cpp`

#### Side Effects:
Access to the AD stack happens by default through the instance() function of the stack. However, for performance reasons (as doced) the access in the `vari` class happens through function  local static references (which are thread_local if needed).

#### Documentation:
Additional comments added where appropriate.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Sebastian Weber

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by wds15** [comment]
Once tests pass this is good for review and merging once the reviewer agrees.

**Comment by seantalts** [comment]
Did you mean to include the `vari` stuff in this one? I still have the same reservations about that part as before - that it alleviates the bottlenecks in our benchmarks but leaves the general pattern potentially untested...

**Comment by wds15** [comment]
I have added in the `vari` class inside the respective functions static references to the AD stack in order to eliminate any extra calls to the function. This is actually recommended on the page which you linked (https://isocpp.org/wiki/faq/ctors#static-init-order):

Quote:
If you’re super performance sensitive and you’re concerned about the overhead of an extra function call on each invocation of X::someMethod() you can set up a static Fred& instead. As you recall, static local are only initialized once (the first time control flows over their declaration), so this will call X::x() only once: the first time X::someMethod() is called:

With `vari` we *are* super-super performance picky! So, yes, I would leave this in (note that this version now does not require any additional build stuff to deal with upstream)... unless you request to delete it, of course.

This is the only place where I did this. In any case, our AD stack should get a refactor which takes our findings into account.

**Comment by ChrisChiasson** [comment]
ifdefs in vari could be eliminated by using a typedef in autodiff stack storage or via other machinery like decltype. That could ease the maintenance burden.

**Comment by wds15** [comment]
@ChrisChiasson ... what are your thoughts on what is proposed in this PR?

**Comment by ChrisChiasson** [comment]
I agree with switching between the static vs magic static implementation.
The extra part that was added in vari makes sense, because caching the
result of instance anywhere will avoid the cost of checking to see if the
static is already created (in the multi threaded case). It does raise the
question: if a thread local static cache of an address of a thread local
static works in vari, what prevents us from doing that in chainable stack
during the relevant typedef instantiation. Wds has probably already tried
that though, possibly giving rise to the static init order notes. Has
everyone else already discussed that in another thread? I have to go work
out now...

**Comment by ChrisChiasson** [comment]
Had an idea on the hand bike... it may be insanity:

Instead of directly instantiating the allocatable stack class template, we
could inherit from it concretely using a non-templated struct (or
non-concretely with a templated struct) containing only a
possibly-thread-local non-static data member initializer (NSDMI). I thought
of this because only C++17 has inline static, but earlier versions have
NSDMI. The struct may still be able to be instantiated via typedef in
chainable stack. If the base template we have all been discussing up to now
makes its thread-local member private, and it's accessor method protected,
we will avoid accidentally calling the base members in other classes.

We could use a better name, but the NSDMI line in the struct might look
like:

(thread_local?) instance_cache = instance();

If it works, this way you could guarantee the initialization order and
solve the performance issues for other classes besides vari.

**Comment by wds15** [comment]
Not sure if I got this right... but what I have tried already is to have a (thread_local) static global variable "instance" which is a reference to the actual AD stack. This reference is initialized using the function approach (static function with static local member). That just crashed on me for reasons, I did not get. In case this is not what you meant, @ChrisChiasson... then maybe some dummy code could help.

**Comment by ChrisChiasson** [comment]
I have to do some FEA today, so please excuse the terrible dummy code. Also, moving to using a struct template with a static member because I think the [weak symbol the linker uses for the static](https://stackoverflow.com/questions/1553854/template-static-variable) may help avoid a compiler or libc++ bug.

Near bottom of autodiffstackstorage.hpp
```
///instance_ would be declared private
///instance() would be declared protected

///then add the following struct near the end
///it may be possible roll the struct member into the base class
template <class CT, class CAT>
struct AutodiffStackSingletonDerived : AutodiffStackSingleton<CT,CAT> {
#ifdef STAN_THREADS
 thread_local
#endif 
static AutodiffStackSingleton<CT,CAT>::AutodiffStackStorage & instance_cache;
}

template <class CT,class CAT>
typename AutodiffStackSingleton<CT,CAT>::AutodiffStackStorage &
AutodiffStackSingletonDerived<CT,CAT>::instance_cache =
 AutodiffStackSingleton<CT,CAT>::instance(); 
```

Then in chainablestack.hpp, the typedef would be:
`typedef AutodiffStackSingletonDerived<vari, chainable_alloc> ChainableStack;`

**Comment by wds15** [comment]
I think I had one try which was exactly as you described, but that made clang fail over.

@seantalts do u prefer to take out the vari trick I did and we merge?

**Comment by seantalts** [comment]
Can you run the timings with and without it? My main worry was that we'd be masking currently unbenchmarked performance regressions with the vari trick.

**Comment by ChrisChiasson** [comment]
If I want to test on a platform that has clang++ and libc++ and that has the bugs we are trying to work around, is a recent Ubuntu 2017 or 2018 x86 release ok to use or will it not have the same bugs as clang on your Mac? I will force it into libc++ mode.

**Comment by wds15** [comment]
Don't bother with those old ubuntus. If you work on a recent Ubuntu, that's fine if you have only that. If you can choose it, then maybe use an ubuntu 16.04 LTS. That one should be sufficiently recent to not have those really odd hickups.

**Comment by ChrisChiasson** [comment]
Newer than that is also ok, right?

**Comment by ChrisChiasson** [comment]
What version of clang are we targeting? LTS only has 3.8, but there seems to be a quick way to add clang-5. https://blog.kowalczyk.info/article/k/how-to-install-latest-clang-5.0-on-ubuntu-16.04-xenial-wsl.html

**Comment by wds15** [comment]
hmm... we don't have a clear statement on that which I am aware of. On travis we use clang 3.8. However, the so-called standard CRAN compiler for macos is clang4. So if things work with 3.8 then great. clang4 is also ok to use. Newer clang versions are only ok if we can show that we have to go there, I think.

**Comment by seantalts** [comment]
For the non-threading case we have the wiki page:
https://github.com/stan-dev/stan/wiki/Supported-C---Compilers-and-Language-Features

Though I think we're having talks of limiting and updating that list soon
hopefully!

**Comment by wds15** [comment]
I think we should go back to the version where `vari` is left in its original state. Things are odd in that I did this trick before (but using a global class reference instead of a function-local reference) and in the global class reference version I saw measurable speedups ... which are now gone in this version. Hence I suggest that we leave that for the moment out.

Timinig comparisons (10 runs each):

No threads:
```
[08:00:44][sebi@sebastians-macbook-pro-1:~/work/performance-tests-cmdstan]$ ./comparePerformance.py nothreads_withTrick_performance.csv ../performance-tests-cmdstan2/nothreads_withoutTrick_performance.csv
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 1.09)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 1.14)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 1.11)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 1.21)
('compilation', 0.23)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 1.15)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.1)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 1.05)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 1.05)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 1.1)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 1.28)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 1.11)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 1.26)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 1.36)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 1.13)
```

Threads:
```
[07:56:25][sebi@sebastians-macbook-pro-1:~/work/performance-tests-cmdstan]$ ./comparePerformance.py threads_withTrick_performance.csv ../performance-tests-cmdstan2/threads_withoutTrick_performance.csv
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 0.92)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 0.83)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 1.02)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 1.07)
('compilation', 0.25)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 0.97)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.01)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 1.04)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 0.98)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 0.92)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 0.87)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 0.97)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 0.98)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 0.93)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 1.0)
```

this branch now vs develop:
```
[08:03:11][sebi@sebastians-macbook-pro-1:~/work/performance-tests-cmdstan2]$ ./comparePerformance.py nothreads_withoutTrick_performance.csv ../performance-tests-cmdstan/develop_performance_10.csv
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 1.06)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 0.94)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 1.01)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 0.95)
('compilation', 1135.56)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 1.0)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.04)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 1.07)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 1.07)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 1.02)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 0.84)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 0.98)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 0.94)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 0.86)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 0.93)
```

All runs were done using clang++ on Apple macOS High Sierra.

**Comment by wds15** [comment]
I am usually running these tests:

- `test/unit/math/rev/mat/functor/gradient_test.cpp`
- all in `test/unit/math/rev/core`

You should run these with clang and g++

**Comment by wds15** [comment]
Bump... would be great if reviewed as then the map_rect concurrent can go in (I just tried and that one then just works)... this will be followed by a map_rect MPI variant which will use threading nested into MPI - and that is performance wise *very* interesting.

This fix is now along the lines discussed, I think.. or was there more?

Thanks!

**Comment by seantalts** [comment]
The fact that removing the "vari trick" kept performance about the same matches the mental model where the function calls are actually compiled away (in a single TU or LTO case, at least) and that the expensive part was actually the guard around checking the initialization status of the static variable in the Meyers singleton pattern. So I'm happy there. Let me see if I can get this reviewed real quick...

File: stan/math/rev/core/autodiffstackstorage.hpp [hunk 1]
```diff
@@ -7,35 +7,30 @@
...
- * Provides a thread_local singleton. Read warnings below!
- * This is useful in a pretty limited set of circumstances, not just because
- * it's thread_local, but also because of "the static init order fiasco"[0].
- * Anywhere this is used, we must be absolutely positive that it doesn't matter
- * when the singleton will get initialized relative to other static variables.
- * In exchange, we get a much more performant singleton pattern than is
- * available with the standard C++11 singleton pattern relying on a function
- * wrapping a static local variable. There has been some discussion on this; see
+ * Provides a thread_local singleton if needed. Read warnings below!
+ * For performance reasons the singletong is a global static for the
```
Comment (seantalts) [inline stan/math/rev/core/autodiffstackstorage.hpp]: "singletong"

File: stan/math/rev/core/vari.hpp [hunk 2]
```diff
@@ -26,6 +26,13 @@ class var;
  * of operations such as addition or subtraction.  These extended
  * classes will store operand variables and propagate derivative
  * information via an implementation of chain().
+ *
```
Comment (seantalts) [inline stan/math/rev/core/vari.hpp]: I think this comment can be removed now

**Comment by wds15** [comment]
Thanks @seantalts ! Let me fix those docs (sorry for overlooking those and thanks for catching). After those are through, I merge.
