### PR TITLE
Bugfix/415 cholesky decompose

### LINKED ISSUE #415: cholesky_decompose for reverse-mode is returning a reference to a local variable in upper-triangular elements of the matrix
#### Summary:
The reverse-mode implementation of `cholesky_decompose` is returning a matrix with `vari` pointers that are pointing to a local variable which falls out of scope.

#### Description:
This is where the vari is created locally:
https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/cholesky_decompose.hpp#L147

Here's where the pointer to the local variable is used:
https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/cholesky_decompose.hpp#L158

When the `vari` is accessed, like in a matrix multiply, the `vari` would have fallen out of scope. This could cause a seg fault or just wrong answers.

One solution is to replace line 147 with:
`vari* dummy = new vari(0.0, false);`

and replace line 158 with:
`L.coeffRef(k, j).vi_ = dummy;`

There may be a better solution.

#### Reproducible Steps:
This is really hard to reproduce since it's returning a reference to a local variable. I was able to reproduce it on my machine on branch: `feature/0187-eigen-3.3` running:
```
./runTests.py test/unit/math/rev/mat/fun/cholesky_decompose_test.cpp
```

But... this isn't guaranteed to fail. It runs fine with optimization set at 0 or if I throw in print statements.

#### Additional Information:
This bug may exist in other matrix functions. I believe we should sweep over them all to make sure we don't have pointers to local variables.

I'm tagging @rtrangucci and @mbrubake because they should know about this bug.

@rtrangucci, can you help me walk through the reverse mode and try to eliminate this if we can find any other instances?

Thanks @bob-carpenter for helping me track this down.

#### Current Version:
v2.12.0

### PR DESCRIPTION
**Pull request by syclik**
#### Submisison Checklist

- [x] Run unit tests: `./runTests.py test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary:
- Fixes #415. Fixes the implementation of `cholesky_decompose` so the upper-triangular elements have a `vari` on the autodiff stack.
- Adds tests to check that functions that return `stan::math::var` have `vari`s that are on the autodiff stack.

#### Intended Effect:
Fixes bug in implementation.

#### How to Verify:
To verify that `cholesky_decompose` is fixed, run:
```
./runTests.py test/unit/math/rev/mat/fun/cholesky_decompose_test.cpp
```

Run the rest of the changed tests.

#### Side Effects:
Fixes a bug.

#### Documentation:
None.

#### Reviewer Suggestions: 
@rtrangucci 

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

File: stan/math/memory/stack_alloc.hpp [hunk 1]
```diff
@@ -247,13 +247,30 @@ namespace stan {
...
+       * Indicates whether the memory in the pointer
+       * is in the stack.
+       *
+       * @param[in] ptr memory location
+       * @return true if the pointer is in the stack,
+       *    false otherwise.
+       */
+      inline bool in_stack(const void* ptr) const {
+        for (size_t i = 0; i < cur_block_; ++i)
+          if (ptr >= blocks_[i] && ptr <= blocks_[i] + sizes_[i])
```
Comment (bob-carpenter) [inline stan/math/memory/stack_alloc.hpp]: I think this should be `ptr < blocks_[i] + sizes_[i]`

File: test/unit/math/memory/stack_alloc_test.cpp [hunk 2]
```diff
@@ -91,3 +91,13 @@ TEST(stack_alloc,alloc) {
   allocator.recover_all();
 
 }
+
+TEST(stack_alloc, in_stack) {
```
Comment (bob-carpenter) [inline test/unit/math/memory/stack_alloc_test.cpp]: I'd suggest doing this in a big loop to make sure we can handle the boundaries across blocks in the memory allocator.  Maybe 100K or something like that would cover everything and still be fast.

File: test/unit/math/rev/mat/fun/corr_matrix_transform_test.cpp [hunk 3]
```diff
@@ -37,3 +38,11 @@ TEST(prob_transform,corr_matrix_jacobian) {
   double log_abs_jacobian_det = log(fabs(determinant(J)));
   EXPECT_FLOAT_EQ(log_abs_jacobian_det,lp.val());
 }
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  int K = 4;
+  int K_choose_2 = 6;
+  Eigen::Matrix<stan::math::var,Eigen::Dynamic,1> X(K_choose_2);
+  X << 1.0, 2.0, -3.0, 1.7, 9.8, -1.2;
+  stan::math::var lp = 0.0;
+  test::check_varis_on_stack(stan::math::corr_matrix_constrain(X,K,lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/corr_matrix_transform_test.cpp]: I think there's also a version without final `lp` argument.

File: test/unit/math/rev/mat/fun/cov_matrix_transform_test.cpp [hunk 4]
```diff
@@ -38,3 +39,14 @@ TEST(prob_transform,cov_matrix_jacobian) {
...
+
+TEST(prob_transform, check_varis_on_stack) {
+  using stan::math::var;
+  int K = 4;
+  unsigned int K_choose_2 = 6;
+  Eigen::Matrix<var,Eigen::Dynamic,1> X(K_choose_2 + K);
+  X << 1.0, 2.0, -3.0, 1.7, 9.8, 
+    -12.2, 0.4, 0.2, 1.2, 2.7;
+  var lp = 0.0;
+  test::check_varis_on_stack(stan::math::cov_matrix_constrain(X,K,lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/cov_matrix_transform_test.cpp]: plus non-lp version.  this should be true for all the `_constrain` functions

File: test/unit/math/rev/mat/fun/divide_test.cpp [hunk 5]
```diff
@@ -216,3 +217,17 @@ TEST(AgradRevMatrix, divide_matrix) {
...
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::var x = 10;
+  stan::math::vector_v v(3);
+  v << -100, 0, 1;
+  stan::math::row_vector_v rv(3);
+  rv << -100, 0, 1;
+  stan::math::matrix_v m(2, 3);
+  m << -100, 0, 1, 20, -40, 2;
+  
+  test::check_varis_on_stack(stan::math::divide(v, x));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/divide_test.cpp]: Did you want to check all the `var` and `double` instantiation combos?

File: test/unit/math/rev/mat/fun/dot_product_test.cpp [hunk 6]
```diff
@@ -240,3 +241,10 @@ TEST(AgradRevMatrix, dot_product_vd_vec) {
   EXPECT_EQ(grad[2], 3);
 }
 
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::vector_v v1(3), v2(3);
+  v1 << 1, 3, -5;
+  v2 << 4, -2, -1;
+  
+  test::check_varis_on_stack(stan::math::dot_product(v1, v2));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/dot_product_test.cpp]: non-var args

File: test/unit/math/rev/mat/fun/elt_divide_test.cpp [hunk 7]
```diff
@@ -218,3 +219,13 @@ TEST(AgradRevMatrix,elt_divide_row_vec_scal_dv) {
...
 }
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  using stan::math::elt_divide;
+  using stan::math::vector_v;
+  vector_v x(2);
+  x << 2, 5;
+  vector_v y(2);
+  y << 10, 100;
+
+  test::check_varis_on_stack(stan::math::elt_divide(x,y));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/elt_divide_test.cpp]: non-`var` instantiations

File: test/unit/math/rev/mat/fun/elt_multiply_test.cpp [hunk 8]
```diff
@@ -176,3 +177,12 @@ TEST(AgradRevMatrix,elt_multiply_matrix_dv) {
...
   EXPECT_FLOAT_EQ(0.0,g[1]);
 }
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  using stan::math::elt_multiply;
+  using stan::math::vector_v;
+  vector_v x(2);
+  x << 2, 5;
+  vector_v y(2);
+  y << 10, 100;
+  test::check_varis_on_stack(stan::math::elt_multiply(x,y));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/elt_multiply_test.cpp]: non-`var` instantiations

File: test/unit/math/rev/mat/fun/mdivide_left_ldlt_test.cpp [hunk 9]
```diff
@@ -373,3 +374,12 @@ TEST(AgradRevMatrix,mdivide_left_ldlt_finite_diff_vd) {
...
 }
 
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::LDLT_factor<stan::math::var,-1,-1> ldlt_Av;
+  stan::math::matrix_v Av(2,2);
+  Av << 2.0, 3.0, 
+    3.0, 7.0;
+  ldlt_Av.compute(Av);
+
+  test::check_varis_on_stack(stan::math::mdivide_left_ldlt(ldlt_Av,Av));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_left_ldlt_test.cpp]: non-`var` instantiations and are there also non-matrix versions here?

File: test/unit/math/rev/mat/fun/mdivide_left_spd_test.cpp [hunk 10]
```diff
@@ -172,3 +173,10 @@ TEST(AgradRevMatrix,mdivide_left_spd_grad_vd) {
     }
   }
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::matrix_v A(2, 2);
+  A << 2.0, 3.0, 
+    3.0, 7.0;
+  test::check_varis_on_stack(stan::math::mdivide_left_spd(A, A));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_left_spd_test.cpp]: non-`var` instantiations and non-matrix instantiations

File: test/unit/math/rev/mat/fun/mdivide_left_test.cpp [hunk 11]
```diff
@@ -172,3 +173,10 @@ TEST(AgradRevMatrix,mdivide_left_grad_vd) {
     }
   }
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::matrix_v A(2,2);
+  A << 2.0, 3.0, 
+    5.0, 7.0;
+  test::check_varis_on_stack(stan::math::mdivide_left(A, A));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_left_test.cpp]: non-`var` instantiations and non-matrix

File: test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp [hunk 12]
```diff
@@ -355,6 +356,14 @@ TEST(AgradRevMatrix,mdivide_left_tri_upper_grad_vd) {
     }
   }
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::matrix_v A(2,2);
+  A << 2.0, 0.0,
+    5.0, 7.0;
+  test::check_varis_on_stack(stan::math::mdivide_left_tri<Eigen::Lower>(A, A));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp]: non-`var` instantiations and non-matrix

File: test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp [hunk 13]
```diff
@@ -355,6 +356,14 @@ TEST(AgradRevMatrix,mdivide_left_tri_upper_grad_vd) {
...
+}
+
 // // FIXME:  Fails in g++ 4.2 -- can't find agrad version of mdivide_left_tri
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp]: We don't support g++ 4.2 --- too early.  Also, in general, we to change `FIXME:` to `TODO(name):`

File: test/unit/math/rev/mat/fun/mdivide_right_ldlt_test.cpp [hunk 14]
```diff
@@ -252,3 +253,18 @@ TEST(AgradRevMatrix, mdivide_right_ldlt_dv) {
...
+  A << 
+    20, 8, -9,  7,  5, 
+    8, 20,  0,  4,  4, 
+    -9, 0,  20,  2,  5, 
+    7, 4,  2,  20, -5, 
+    5, 4,  5, -5,  20;
+  stan::math::LDLT_factor<stan::math::var, -1, -1> ldlt_A;
+  ldlt_A.compute(A);
+  
+  test::check_varis_on_stack(stan::math::mdivide_right_ldlt(b, ldlt_A));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_right_ldlt_test.cpp]: non-`var` instantiations and non-matrix

File: test/unit/math/rev/mat/fun/mdivide_right_test.cpp [hunk 15]
```diff
@@ -34,3 +35,10 @@ TEST(AgradRevMatrix,mdivide_right_val) {
   EXPECT_NEAR(0.0,I(1,0).val(),1.0E-12);
   EXPECT_NEAR(1.0,I(1,1).val(),1.0e-12);
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::matrix_v m(2,2);
+  m << 2.0, 3.0, 
+    5.0, 7.0;
+  test::check_varis_on_stack(stan::math::mdivide_right(m, m));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/mdivide_right_test.cpp]: non-`var` instantiations and non-matrix

File: test/unit/math/rev/mat/fun/multiply_test.cpp [hunk 16]
```diff
@@ -1669,3 +1670,23 @@ TEST(AgradRevMatrix, multiply_vector_row_vector_grad_ex_vd) {
...
 }
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::matrix_v m(3, 3);
+  m << 1, 2, 3, 4, 5, 6, 7, 8, 9;
+  stan::math::vector_v v(3);
+  v << 10, 20, 30;
+  stan::math::row_vector_v rv(3);
+  rv << 100, 200, 300;
+  stan::math::var s = 1;
+  test::check_varis_on_stack(stan::math::multiply(m, m));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/multiply_test.cpp]: non-`var` instantiations

File: test/unit/math/rev/mat/fun/ordered_transform_test.cpp [hunk 17]
```diff
@@ -44,3 +45,9 @@ TEST(prob_transform,ordered_jacobian_ad) {
   EXPECT_FLOAT_EQ(log_abs_jacobian_det, lp);
 }
 
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  Eigen::Matrix<stan::math::var,Eigen::Dynamic,1> x(3);
+  x << -12.0, 3.0, -1.9;
+  stan::math::var lp = 0.0;
+  test::check_varis_on_stack(stan::math::ordered_constrain(x,lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/ordered_transform_test.cpp]: non-lp version

File: test/unit/math/rev/mat/fun/positive_ordered_transform_test.cpp [hunk 18]
```diff
@@ -43,3 +44,10 @@ TEST(prob_transform,positive_ordered_jacobian_ad) {
   double log_abs_jacobian_det = log(fabs(determinant(J)));
   EXPECT_FLOAT_EQ(log_abs_jacobian_det, lp);
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  Eigen::Matrix<stan::math::var,Eigen::Dynamic,1> x(3);
+  x << -12.0, 3.0, -1.9;
+  stan::math::var lp = 0.0;
+  test::check_varis_on_stack(stan::math::positive_ordered_constrain(x,lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/positive_ordered_transform_test.cpp]: non-lp version

File: test/unit/math/rev/mat/fun/simplex_transform_test.cpp [hunk 19]
```diff
@@ -42,3 +43,9 @@ TEST(probTransform,simplex_jacobian) {
 
   EXPECT_FLOAT_EQ(log_det_J, lp.val());
 }
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  stan::math::vector_v y(3);
+  y << 2, 3, -1;
+  stan::math::var lp = 0;
+  test::check_varis_on_stack(stan::math::simplex_constrain(y, lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/simplex_transform_test.cpp]: non-lp version

File: test/unit/math/rev/mat/fun/subtract_test.cpp [hunk 20]
```diff
@@ -199,3 +200,19 @@ TEST(AgradRevMatrix, subtract_matrix_matrix_exception) {
...
+  stan::math::matrix_v m(2, 2);
+  m << 1, 2, 3, 4;
+
+  stan::math::vector_v v(3);
+  v << 1, 2, 3;
+
+  stan::math::row_vector_v rv(2);
+  rv << 1, 2;
+
+  test::check_varis_on_stack(stan::math::subtract(m, m));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/subtract_test.cpp]: lots more combinatorics here with non-`lp` matrices and vectors

File: test/unit/math/rev/mat/fun/trace_gen_inv_quad_form_ldlt_test.cpp [hunk 21]
```diff
@@ -1018,3 +1019,51 @@ TEST(AgradRevMatrix, trace_gen_inv_quad_form_ldlt_grad_vvv_basic) {
...
+        3.0,  2.0, 1.0, 112.0;
+  cd.setIdentity(2,2);
+  cv.setIdentity(2,2);
+
+  stan::math::LDLT_factor<double,-1,-1> ldlt_ad;
+  stan::math::LDLT_factor<stan::math::var,-1,-1> ldlt_av;
+  ldlt_av.compute(av);
+  ldlt_ad.compute(ad);
+  
+  test::check_varis_on_stack(stan::math::trace_gen_inv_quad_form_ldlt(cv, ldlt_av, bv));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/trace_gen_inv_quad_form_ldlt_test.cpp]: i think thre are non-`var` instantiations here, but I'm not sure

File: test/unit/math/rev/mat/fun/unit_vector_constrain_test.cpp [hunk 22]
```diff
@@ -58,3 +59,12 @@ TEST(AgradRevUnitVectorConstrain, exceptions) {
...
   EXPECT_THROW(unit_vector_constrain(x),std::domain_error);
 }
+
+TEST(AgradRevMatrix, check_varis_on_stack) {
+  using stan::math::var;
+  using stan::math::to_var;
+  Eigen::Matrix<var, Eigen::Dynamic, 1> y(3);
+  y << 0.0, 3.0, -1.0;
+
+  test::check_varis_on_stack(stan::math::unit_vector_constrain(y));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/unit_vector_constrain_test.cpp]: should be an `lp` version, too

File: test/unit/math/rev/mat/fun/unit_vector_transform_test.cpp [hunk 23]
```diff
@@ -49,3 +50,12 @@ TEST(probTransform,unit_vector_jacobian) {
...
 }
 
+TEST(probTransform, check_varis_on_stack) {
+  using stan::math::to_var;
+  using stan::math::var;
+  Matrix<var,Dynamic,1> y(3);
+  y << 2, 3, -1;
+  
+  var lp(0);
+  test::check_varis_on_stack(stan::math::unit_vector_constrain(y, lp));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/fun/unit_vector_transform_test.cpp]: not sure why this is in a different file than the last test as they're of the same function

File: test/unit/math/rev/mat/prob/multi_normal_cholesky_test.cpp [hunk 24]
```diff
@@ -20,3 +19,24 @@ TEST(ProbDistributionsMultiNormalCholesky,MultiNormalVar) {
...
+  Matrix<double,Dynamic,1> y(3,1);
+  y << 2.0, -2.0, 11.0;
+  Matrix<double,Dynamic,1> mu(3,1);
+  mu << 1.0, -1.0, 3.0;
+  Matrix<double,Dynamic,Dynamic> Sigma(3,3);
+  Sigma << 9.0, -3.0, 0.0,
+    -3.0,  4.0, 0.0,
+    0.0, 0.0, 5.0;
+  Matrix<double,Dynamic,Dynamic> L = Sigma.llt().matrixL();
+  test::check_varis_on_stack(stan::math::multi_normal_cholesky_log(to_var(y), to_var(mu), to_var(L)));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/prob/multi_normal_cholesky_test.cpp]: testing both propto and not?

File: test/unit/math/rev/mat/prob/multi_normal_prec_test.cpp [hunk 25]
```diff
@@ -18,3 +19,23 @@ TEST(ProbDistributionsMultiNormalPrec,MultiNormalVar) {
...
+    -3.0,  4.0, 0.0,
+    0.0, 0.0, 5.0;
+  Matrix<double,Dynamic,Dynamic> L = Sigma.inverse();
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(to_var(y), to_var(mu), to_var(L)));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(to_var(y), to_var(mu), L));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(to_var(y), mu, to_var(L)));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(to_var(y), mu, L));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(y, to_var(mu), to_var(L)));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(y, to_var(mu), L));
+  test::check_varis_on_stack(stan::math::multi_normal_prec_log(y, mu, to_var(L)));
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/prob/multi_normal_prec_test.cpp]: propto and not

File: test/unit/math/rev/mat/util.hpp [hunk 26]
```diff
@@ -0,0 +1,30 @@
+#ifndef TEST_UNIT_MATH_REV_MAT_UTIL_HPP
+#define TEST_UNIT_MATH_REV_MAT_UTIL_HPP
+
+#include <stan/math/rev/mat.hpp>
+#include <gtest/gtest.h>
+#include <test/unit/math/rev/arr/util.hpp>
+
+namespace test {
+
+  void check_varis_on_stack(const stan::math::matrix_v& x) {
```
Comment (bob-carpenter) [inline test/unit/math/rev/mat/util.hpp]: Make this all one function

```
template <int R, int C>
void check_varis_on_stack(const Eigen::Matrix<stan::math::var, R, C>& x) {
  for (int i = 0; i < x.size(); ++i) ...
}
```

File: test/unit/math/rev/scal/fun/binary_log_loss_test.cpp [hunk 27]
```diff
@@ -95,3 +95,8 @@ TEST(AgradRev,binary_log_loss_NaN) {
   binary_log_loss_fun binary_log_loss_;
   test_nan(binary_log_loss_,false,true);
 }
+
+TEST(AgradRev, check_varis_on_stack) {
+  AVAR y_hat = 0.0;
+  test::check_varis_on_stack(stan::math::binary_log_loss(0, y_hat));
```
Comment (bob-carpenter) [inline test/unit/math/rev/scal/fun/binary_log_loss_test.cpp]: all 3 instantiations with `var` component needed

File: test/unit/math/rev/scal/fun/gamma_q_test.cpp [hunk 28]
```diff
@@ -91,3 +91,11 @@ TEST(AgradRev, gamma_q_nan) {
   gamma_q_fun gamma_q_;
   test_nan(gamma_q_,3.0,5.0,false,true);
 }
+
+TEST(AgradRev, check_varis_on_stack) {
+  AVAR a = 0.5;
+  AVAR b = 1.0;
+  test::check_varis_on_stack(stan::math::gamma_q(a,b));
```
Comment (bob-carpenter) [inline test/unit/math/rev/scal/fun/gamma_q_test.cpp]: spaces after commas!

File: test/unit/math/rev/scal/fun/int_step_test.cpp [hunk 29]
```diff
@@ -1,6 +1,6 @@
 #include <stan/math/rev/scal.hpp>
 #include <gtest/gtest.h>
-#include <test/unit/math/rev/mat/fun/util.hpp>
+#include <test/unit/math/rev/scal/fun/util.hpp>
```
Comment (bob-carpenter) [inline test/unit/math/rev/scal/fun/int_step_test.cpp]: Nice!

File: test/unit/math/rev/scal/fun/modified_bessel_second_kind_test.cpp [hunk 30]
```diff
@@ -35,3 +35,9 @@ TEST(AgradRev,modified_bessel_second_kind_NaN) {
   modified_bessel_second_kind_fun modified_bessel_second_kind_;
   test_nan(modified_bessel_second_kind_,false,true);
 }
+
+TEST(AgradRev, check_varis_on_stack) {
+  int a(1);
+  AVAR b(4.0);
+  test::check_varis_on_stack(stan::math::modified_bessel_second_kind(a,b));
```
Comment (bob-carpenter) [inline test/unit/math/rev/scal/fun/modified_bessel_second_kind_test.cpp]: space after commas

File: test/unit/math/rev/scal/fun/rising_factorial_test.cpp [hunk 31]
```diff
@@ -82,3 +82,9 @@ TEST(AgradRev, rising_factorial_nan) {
   rising_factorial_fun rising_factorial_;
   test_nan(rising_factorial_,3.0,5.0,false,true);
 }
+
+TEST(AgradRev, check_varis_on_stack) {
+  double a(1);
+  AVAR b(4.0);
+  test::check_varis_on_stack(stan::math::rising_factorial(b,a));
```
Comment (bob-carpenter) [inline test/unit/math/rev/scal/fun/rising_factorial_test.cpp]: need other two permutations of `var` and `double`

File: test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp (hunk 13 above)
Comment (syclik) [inline test/unit/math/rev/mat/fun/mdivide_left_tri_test.cpp]: I'm removing the comment.

Agreed with `TODO(name):`.

File: test/unit/math/rev/mat/fun/divide_test.cpp (hunk 5 above)
Comment (syclik) [inline test/unit/math/rev/mat/fun/divide_test.cpp]: I did... I don't know why the diff isn't showing the changes here.

File: test/unit/math/rev/mat/fun/dot_product_test.cpp (hunk 6 above)
Comment (syclik) [inline test/unit/math/rev/mat/fun/dot_product_test.cpp]: Same here. I've added the non-var args.

**Comment by syclik** [comment]
@bob-carpenter, I fixed all the spots you noticed. Thanks for putting extra eyes on it.
