### PR TITLE
Evaluate expressions in poisson functions (Issue #2413)

### LINKED ISSUE #2413: Poisson cdf functions failing expression tests
## Description

There's a problem with the poisson cdf functions.

Example here: https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-838/8/pipeline/

Edit: Can run these tests with stuff like:
```
./runTests.py test/expressions --only-functions poisson_lcdf
```

I think I have a fix but it shows up differently on my computer and so maybe it's something else. The tests fail on my computer with g++ but not clang++.

#### Current Version:
v4.0.1

### PR DESCRIPTION
**Pull request by bbbales2**
## Summary

Hopefully fixes #2413 

## Tests

The expression tests catch these. Only works for g++ though? For some reason clang++ passes. Not sure if it's possible to do better.

## Release notes

- Fix bug with expressions in poisson distribution functions

## Checklist

- [x] Math issue #2413

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

File: stan/math/prim/prob/poisson_lcdf.hpp [hunk 1]
```diff
@@ -52,7 +52,7 @@ return_type_t<T_rate> poisson_lcdf(const T_n& n, const T_rate& lambda) {
     return ops_partials.build(negative_infinity());
   }
 
-  const auto& log_Pi = log(gamma_q(n_val + 1.0, lambda_val));
+  const auto& log_Pi = to_ref(log(gamma_q(n_val + 1.0, lambda_val)));
```
Comment (t4c1) [inline stan/math/prim/prob/poisson_lcdf.hpp:55]:
```suggestion
  const auto& log_Pi = to_ref_if<!is_constant_all<T_rate>::value
>(log(gamma_q(n_val + 1.0, lambda_val)));
```

This is actually a (performance) bug that needs fixing. All other changes you did are just forcing evaluation even when we don't need to evaluate and should be reverted. 

Anyway this should not trigger expression tests to fail, so I think changes from this PR will not help with that.

**Review by t4c1 — CHANGES_REQUESTED** [review]

File: stan/math/prim/prob/poisson_lcdf.hpp (hunk 1 above)
Comment (bbbales2) [reply stan/math/prim/prob/poisson_lcdf.hpp]: @t4c1 agreed. I reverted this part. I think this had something to do with the rvalue `n_val + 1.0` (where n_val is an integer). I made the expression in the lambda in apply_scalar_binary capture by value instead of by reference.

Rok tells me you figured out something on this, so if it's something better happy to go with that. I just wanted to get my solution up so you'd be proud of me for figuring out rvalues and expressions.

Comment (t4c1) [reply stan/math/prim/prob/poisson_lcdf.hpp]: That something is actually almost exactly what you just pushed. I definitely am proud of you :D.

Comment (t4c1) [reply stan/math/prim/prob/poisson_lcdf.hpp]: However you should still include the `to_ref_if` I suggested here. While it wont affect tests passing it should make this a bit faster.

Comment (bbbales2) [reply stan/math/prim/prob/poisson_lcdf.hpp]: :bowtie:

Oh I missed that that `to_ref_if` was separate. I added it.

**Comment by bgoodri** [comment]
Does anyone know a way to fix the performance issues that we were having with `poisson_lcdf` but without 25959a24bdd00b9b8f623e422fd98e310895df4b that was merged with this PR? The `poisson_lcdf` function is fine in the current version of Stan Math but would segfault in previous versions when the size of the expectation is longer than the random variable, but only when compiled with `-O2` or `-O3`. I am pretty sure the culprit is the `to_ref_if` thing because `gamma_q` is fine when the second argument is longer than the first. It is just when `poisson_lcdf` calls `to_ref_if<!is_constant_all<T_rate>::value>(log(gamma_q(n_val + 1.0, lambda_val)))` with a longer `lambda_val` than `n_val` that the segfault happens.

```
StanHeaders::stanFunction("poisson_lcdf", n = 10L, lambda = list(1,2))
[Detaching after fork from child process 14363]
using C++ compiler: ‘g++-8 (Debian 8.3.0-6) 8.3.0’
using C++17

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff010067a in boost::math::gamma_q<double, double, boost::math::policies::policy<boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> > (z=<error reading variable: Cannot access memory at address 0x4000000000000000>, a=<optimized out>)
    at /home/ben/r-devel/library/BH/include/boost/math/special_functions/gamma.hpp:2103
2103       gamma_q(T1 a, T2 z)
(gdb) bt
#0  0x00007ffff010067a in boost::math::gamma_q<double, double, boost::math::policies::policy<boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> > (z=<error reading variable: Cannot access memory at address 0x4000000000000000>, a=<optimized out>)
    at /home/ben/r-devel/library/BH/include/boost/math/special_functions/gamma.hpp:2103
#1  boost::math::gamma_q<double, double> (z=<error reading variable: Cannot access memory at address 0x4000000000000000>, a=<optimized out>)
    at /home/ben/r-devel/library/BH/include/boost/math/special_functions/gamma.hpp:2105
#2  stan::math::gamma_q (a=<error reading variable: Cannot access memory at address 0x4000000000000000>, x=<optimized out>)
    at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/fun/gamma_q.hpp:55
#3  stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}::operator()<double, double>(double const&, double const&) const (this=<optimized out>, c=<optimized out>, d=<optimized out>) at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/fun/gamma_q.hpp:70
#4  stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}::operator()<double>(double const&) const (v=<optimized out>, 
    this=<optimized out>) at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/functor/apply_scalar_binary.hpp:232
#5  Eigen::internal::unary_evaluator<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, Eigen::internal::IndexBased, double>::coeff(long, long) const (col=0, row=0, 
    this=<optimized out>) at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:543
#6  Eigen::internal::evaluator<stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> >::coeff(long, long) const (col=0, 
    row=0, this=<optimized out>) at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/meta/holder.hpp:189
#7  Eigen::internal::unary_evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const>, Eigen::internal::IndexBased, double>::coeff(long, long) const (col=0, row=0, this=<optimized out>)
    at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:543
#8  Eigen::internal::redux_evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const> >::coeffByOuterInner(long, long) const (inner=0, outer=0, this=<optimized out>) at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/Redux.h:381
#9  Eigen::internal::redux_impl<Eigen::internal::scalar_sum_op<double, double>, Eigen::internal::redux_evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const> >, 0, 0>::run(stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const&, Eigen::internal::scalar_sum_op<double, double> const&) (func=..., mat=...) at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/Redux.h:194
#10 Eigen::DenseBase<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const> >::redux<Eigen::internal::scalar_sum_op<double, double> >(Eigen::internal::scalar_sum_op<double, double> const&) const (func=..., this=<optimized out>) at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/Redux.h:418
#11 Eigen::DenseBase<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const> >::sum() const (this=<optimized out>) at /home/ben/r-devel/library/RcppEigen/include/Eigen/src/Core/Redux.h:453
#12 stan::math::sum<Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<double>, stan::math::Holder<Eigen::CwiseUnaryOp<stan::math::apply_scalar_binary<double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}, (void*)0, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&, stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&)::{lambda(auto:1&, auto:2&, auto:2&)#1}::operator()<{lambda(auto:1 const&, auto:2 const&)#1}, double const, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>(stan::math::gamma_q<double, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > >, (void*)0>(double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&)::{lambda(auto:1 const&, auto:2 const&)#1}&&, double const&, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const&) const::{lambda(auto:1 const&)#1}, Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0> > > const>, {lambda(auto:1 const&, auto:2 const&)#1}> const>, (void*)0> (m=...) at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/fun/sum.hpp:47
#13 stan::math::poisson_lcdf<int, std::vector<double, std::allocator<double> > > (n=@0x7fffffff8adc: 10, lambda=std::vector of length 2, capacity 2 = {...}) at /home/ben/r-devel/library/StanHeaders/include/stan/math/prim/prob/poisson_lcdf.hpp:57
#14 0x00007ffff00f0bba in poisson_lcdf (n=<optimized out>, lambda=...) at /home/ben/r-devel/library/Rcpp/include/Rcpp/internal/Proxy_Iterator.h:93
#15 0x00007ffff00f0dcb in sourceCpp_1_poisson_lcdf (nSEXP=<optimized out>, lambdaSEXP=<optimized out>) at /home/ben/r-devel/library/Rcpp/include/Rcpp/InputParameter.h:74
#16 0x000055555564834a in R_doDotCall (fun=<optimized out>, nargs=<optimized out>, cargs=<optimized out>, call=0x55555b7dd540) at dotcode.c:871
#17 0x000055555564881e in do_dotcall (call=0x55555b7dd540, op=<optimized out>, args=<optimized out>, env=<optimized out>) at dotcode.c:1551
#18 0x0000555555693855 in Rf_eval (e=<optimized out>, rho=rho@entry=0x55555b7ad8c0) at eval.c:1253
#19 0x00005555556952ff in R_execClosure (call=call@entry=0x55555b7ad6c8, newrho=newrho@entry=0x55555b7ad8c0, sysparent=<optimized out>, rho=rho@entry=0x5555559fe038, arglist=arglist@entry=0x55555b7ad7a8, op=op@entry=0x55555b7c3ce8) at eval.c:2365
#20 0x000055555569615e in applyClosure_core (call=call@entry=0x55555b7ad6c8, op=op@entry=0x55555b7c3ce8, arglist=<optimized out>, rho=rho@entry=0x5555559fe038, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2253
#21 0x0000555555696957 in Rf_applyClosure (call=call@entry=0x55555b7ad6c8, op=op@entry=0x55555b7c3ce8, arglist=<optimized out>, rho=rho@entry=0x5555559fe038, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2273
#22 0x0000555555693423 in Rf_eval (e=e@entry=0x55555b7ad6c8, rho=rho@entry=0x5555559fe038) at eval.c:1273
#23 0x00005555556147b4 in do_docall (call=0x55555b7ad6c8, op=<optimized out>, args=0x555555f0d0b8, rho=<optimized out>) at coerce.c:2764
#24 0x0000555555682122 in bcEval (body=body@entry=0x555556ac4830, rho=rho@entry=0x55555b7b1300, useCache=useCache@entry=TRUE) at eval.c:7735
#25 0x0000555555693290 in Rf_eval (e=0x555556ac4830, rho=rho@entry=0x55555b7b1300) at eval.c:1146
#26 0x00005555556952ff in R_execClosure (call=call@entry=0x555557dfebe0, newrho=newrho@entry=0x55555b7b1300, sysparent=<optimized out>, rho=rho@entry=0x555557e09700, arglist=arglist@entry=0x55555b7b1108, op=op@entry=0x555556ac8510) at eval.c:2365
#27 0x000055555569615e in applyClosure_core (call=0x555557dfebe0, op=op@entry=0x555556ac8510, arglist=<optimized out>, rho=rho@entry=0x555557e09700, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2253
#28 0x0000555555696957 in Rf_applyClosure (call=<optimized out>, op=op@entry=0x555556ac8510, arglist=<optimized out>, rho=rho@entry=0x555557e09700, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2273
#29 0x0000555555689ef2 in bcEval (body=body@entry=0x555557de0aa8, rho=rho@entry=0x555557e09700, useCache=useCache@entry=TRUE) at eval.c:7706
#30 0x0000555555693290 in Rf_eval (e=0x555557de0aa8, rho=rho@entry=0x555557e09700) at eval.c:1146
#31 0x00005555556952ff in R_execClosure (call=call@entry=0x555557bf2328, newrho=newrho@entry=0x555557e09700, sysparent=<optimized out>, rho=rho@entry=0x5555559fe038, arglist=arglist@entry=0x555557e09a10, op=op@entry=0x555557de13d8) at eval.c:2365
#32 0x000055555569615e in applyClosure_core (call=call@entry=0x555557bf2328, op=op@entry=0x555557de13d8, arglist=<optimized out>, rho=rho@entry=0x5555559fe038, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2253
#33 0x0000555555696957 in Rf_applyClosure (call=call@entry=0x555557bf2328, op=op@entry=0x555557de13d8, arglist=<optimized out>, rho=rho@entry=0x5555559fe038, suppliedvars=<optimized out>, unpromise=unpromise@entry=TRUE) at eval.c:2273
#34 0x0000555555693423 in Rf_eval (e=e@entry=0x555557bf2328, rho=rho@entry=0x5555559fe038) at eval.c:1273
#35 0x00005555556c72c5 in Rf_ReplIteration (state=<optimized out>, browselevel=<optimized out>, savestack=<optimized out>, rho=<optimized out>) at main.c:262
#36 Rf_ReplIteration (rho=0x5555559fe038, savestack=0, browselevel=0, state=0x7fffffffcb40) at main.c:198
#37 0x00005555556c75d1 in R_ReplConsole (rho=0x5555559fe038, savestack=0, browselevel=0) at main.c:314
#38 0x00005555556c7662 in run_Rmainloop () at main.c:1216
#39 0x00005555556c76ae in Rf_mainloop () at main.c:1223
#40 0x00005555555bc708 in main (ac=ac@entry=2, av=av@entry=0x7fffffffdc98) at Rmain.c:29
#41 0x00007ffff714b09b in __libc_start_main (main=0x5555555bc6f0 <main>, argc=2, argv=0x7fffffffdc98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc88) at ../csu/libc-start.c:308
#42 0x00005555555bc73a in _start () at Rmain.c:30
```

**Comment by SteveBronder** [comment]
@bgoodri I'll take a look at this

**Comment by bgoodri** [comment]
@SteveBronder To what extent do you think it would be feasible to take the prob/ folder from the current Stan Math release with your PR that implemented the new operands and partials and stick that into the previous Stan Math release without having to do a ton of other backporting?

**Comment by SteveBronder** [comment]
@bgoodri not sure I'm following, does that fix the issue?

**Comment by SteveBronder** [comment]
> It is just when poisson_lcdf calls to_ref_if<!is_constant_all<T_rate>::value>(log(gamma_q(n_val + 1.0, lambda_val))) with a longer lambda_val than n_val that the segfault happens

Do you mean when `n_val` is a scalar and `lambda_val` is a vector? Otherwise `check_constant_sizes` should throw an error

**Comment by bgoodri** [comment]
I was just speculating since the problem does not exist in Stan Math currently that I might be able to backport your PR that changed operands and partials + prob/ .

**Comment by bgoodri** [comment]
Yes, in `StanHeaders::stanFunction("poisson_lcdf", n = 10L, lambda = list(1,2))` `lambda` becomes a `std::vector<double>`. It can also be triggered with an `EigenVectorXd` for `lambda` but the backtrace is (even) more of a mess.

**Comment by SteveBronder** [comment]
We could do the backport if that fixes the issue. imo that PR is mostly just a find replace with the new operands and partials. Though if it's reading memory incorrectly I wonder if it's an issue with `apply_scalar_binary`?

@WardBrian how far are we till the next release? Ben if it's like a month away would it be easier to just wait and add the latest version of stan math to rstan? Or is that not feasible / a bigger hassle?

**Comment by SteveBronder** [comment]
Also does this only happen in rstan or can this be replicated with just plain c++?

**Comment by SteveBronder** [comment]
I have a repo here you can bring in versions of stan math to test and whatnot

https://github.com/SteveBronder/stan-perf

**Comment by WardBrian** [comment]
> how far are we till the next release

It should be in January. Probably closer to the end of the month since planning will start after the holidays at this point

**Comment by bgoodri** [comment]
> Also does this only happen in rstan or can this be replicated with just plain c++?

It is StanHeaders unmodified from release before current although we have seen it in a geostan model with a censored poison likelihood at a scalar with multiple censored observations. The stanFunction function is plain C++17 with an exposure to rstan from Rcpp. We need a temporary fix 2 months ago even if it slows down the execution time.

**Comment by SteveBronder** [comment]
imo I think we can just take the small performance hit and use `to_ref` here instead of `to_ref_if`

**Comment by SteveBronder** [comment]
At least as a quick fix

**Comment by bgoodri** [comment]
Changing line 55 from
```
const auto& log_Pi = to_ref_if<!is_constant_all<T_rate>::value>(
      log(gamma_q(n_val + 1.0, lambda_val)));
```
to
```
const auto& log_Pi = to_ref(log(gamma_q(n_val + 1.0, lambda_val)));
```
avoids the crash. I didn't test the speed, but no one is anticipating any unanticipated consequences from changing that? Do I need to do something similar for any of the other distributions?

**Comment by SteveBronder** [comment]
I think its fine. I'm going to look into `apply_scalar_binary` and check to see if that might be the source of the error. It could be that function is trying to return an expression and at high enough compiler levels a temporary is falling out of scope

**Comment by SteveBronder** [comment]
@bgoodri could you try changing this line back to not taking a reference on `x`? that could be causing the temporary `n _val+ 1` to fall out of scope

https://github.com/stan-dev/math/pull/2414/files#diff-fd86a7ac70be5ef26ba5b4e659ebd8fdab0e916b63b03c9c21499fbb157d7d09L216

**Comment by SteveBronder** [comment]
@WardBrian Do the expression tests get checked at O3? We should probably do that even if it takes longer to compile.

**Comment by bgoodri** [comment]
The apply_binary.hpp file changed a lot between the time #2413 was merged and when the release before last happened. What would you want me to change in the 4.6.2 version of apply_binary.hpp?
https://github.com/stan-dev/math/blob/v4.6.2/stan/math/prim/functor/apply_scalar_binary.hpp
The previous crash can also happen at -O2.

**Comment by WardBrian** [comment]
> Do the expression tests get checked at O3?

We run them at `-O0`, and as far as I can tell this has been true since they were added (i.e., it isn't an optimization we tried to make later). If I'm understanding the issue here correctly, I also don't think they ever would have caught it, since I believe the expression tests always pass arguments of the same length?

**Comment by SteveBronder** [comment]
By different lengths Ben meant a scalar and vector. The code should and does fail for vectors of different lengths

**Review by bob-carpenter — COMMENTED** [review]
This PR worries me because it moved from pass by reference to pass by copy.  I see it has already been merged, but I'd like to understand why the reference was causing a problem and if there is an alternative to passing by value that would be workable.
