### PR TITLE
Fix for to_matrix(row_vector) and to_matrix(vector)

### LINKED ISSUE #2669: Compilation error
**Describe the bug**

I got my first situation now where the initial syntax check or so that stan is doing passes, but the compilation fails. And I don’t really understand why or how I can start to debug this - I tried to change the code for an hour and it still fails. I cannot reproduce the compilation error when having the single function in a separate stan file.

**To Reproduce**

Apologies - I could not reproduce this bug so far in a minimum example. 
The problem comes down to a block of code like this:

```
matrix fun(matrix time) {
    matrix[rows(time), cols(time)] result;
    real val;
    val = time[1, 2];
    return result;
}
```

(note that this is simplified but it fails like this) It starts compiling but after few seconds gives a huge error message, that ends with:

```
stan/src/stan/model/indexing/rvalue.hpp:55:10: note:   template argument deduction/substitution failed:
/tmp/RtmpiGD5kC/model-4fe3695a40a9.hpp:436:17: note:   candidate expects 2 arguments, 4 provided
  436 |     val = rvalue(time, "time", index_uni(1), index_uni(2));
      |           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [make/program:58: /tmp/RtmpiGD5kC/model-4fe3695a40a9] Fehler 1
Fehler: An error occured during compilation! See the message above for more information.
```

**Expected behavior**

I would have expected that the code compiles without error.

**Operating system**

Ubuntu 20.04.3 LTS

**CmdStanR version number**

CmdStan 2.28.2 via cmdstanr_0.4.0

**Additional context**

Compiler/Toolkit: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Summary

Fixes #2669 by fixing `to_matrix(row_vector)` and `to_matrix(vector)`, which were previously just forwarded. This bug surfaces if to_matrix() is used in a call to a UDF.

## Tests

/

## Side Effects

/

## Release notes

Fixed a bug with `to_matrix(row_vector)` and `to_matrix(vector)`.

## Checklist

- [x] Math issue #2669 

- [x] Copyright holder: Rok Češnovar

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@SteveBronder any chance you could take a look at why this is failing in the sanitizer? I have exhausted my knowledge :)

**Comment by andrjohns** [comment]
I think is a jenkins issue rather than PR-related, since I've gotten the same error in the gradients draft PR

**Comment by rok-cesnovar** [comment]
Ah, thanks! I think I found the cause. We switched from g++ to clang for the sanitize test. Will fix here.

**Comment by SteveBronder** [comment]
@rok-cesnovar sorry missed this yes I'll look at this tmrw morning I think I see what's going on

**Comment by rok-cesnovar** [comment]
This is now passing tests. I had to switch to the old testing agent (the Gelman Linux for the full unit test). Lets get this patch out and then proceed with addressing that without a time crunch.

For the testing aspect of this PR, I added the model that was mentioned in the issue to the stanc3 test models: https://github.com/stan-dev/stanc3/pull/1138

With this branch, the model compiles fine.

@SteveBronder mind giving this a quick look? Thanks!

File: stan/math/prim/fun/to_matrix.hpp [hunk 1]
```diff
@@ -11,20 +11,41 @@ namespace math {
...
- * The runtime dimensions will be the same as the input.
+ * Eigen matrix.
  *
  * @tparam EigMat type of the matrix
  *
  * @param x matrix
  * @return the matrix representation of the input
  */
-template <typename EigMat, require_eigen_t<EigMat>* = nullptr>
+template <typename EigMat, require_eigen_matrix_dynamic_t<EigMat>* = nullptr>
```
Comment (SteveBronder) [inline stan/math/prim/fun/to_matrix.hpp:21]: I'd use `require_eigen_dense_dynamic_t` here

File: stan/math/prim/fun/to_matrix.hpp [hunk 2]
```diff
@@ -11,20 +11,41 @@ namespace math {
...
+  to_matrix(const EigMat& matrix) {
+  using T = value_type_t<EigMat>;
+  Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>
+      res(matrix.rows(), matrix.cols());
+  Eigen::Map<
+      Eigen::Matrix<T, EigMat::RowsAtCompileTime, EigMat::ColsAtCompileTime>>
+      res_map(res.data(), matrix.rows(), matrix.cols());
+  res_map = matrix;
+  return res;
+}
```
Comment (SteveBronder) [inline stan/math/prim/fun/to_matrix.hpp:47]: You can just do this in one line like 

```cpp
template <typename EigVec, require_eigen_vector_t<EigVec>* = nullptr>
inline auto to_matrix(EigVec&& matrix) {
  return Eigen::Matrix<value_type_t<EigMat>, Eigen::Dynamic, Eigen::Dynamic>(std::forward<EigVec>(matrix));
}
```

**Review by SteveBronder — CHANGES_REQUESTED** [review]
Two little things, sorry for my delay on this!

File: stan/math/prim/fun/to_matrix.hpp (hunk 2 above)
Comment (rok-cesnovar) [reply stan/math/prim/fun/to_matrix.hpp]: Nice! Done.

File: stan/math/prim/fun/to_matrix.hpp (hunk 1 above)
Comment (rok-cesnovar) [reply stan/math/prim/fun/to_matrix.hpp]: Thanks. 

Unrelated: Should we do the same with UDF requires in stanc3. Maybe do it as part of https://github.com/stan-dev/stanc3/pull/1107

**Comment by rok-cesnovar** [comment]
Thanks Steve. Much appreciated! Added your suggestions.

@serban-nicusor-toptal Once this is merged we can start with the patch release.

**Review by SteveBronder — APPROVED** [review]
Good!
