### PR TITLE
remove discontinuity in lub_constrain; fixes #1441

### LINKED ISSUE #1441: lub_constrain boundary behaviour
## Description

Remove the conditional

```
 if ((x > NEGATIVE_INFTY) && (inv_logit_x == 0))
    inv_logit_x = 1e-15;
```

from the definition of `lub_constrain()` in `stan/math/prim/scal/fun/lub_constrain.hpp`.

### Background

The parameter constraining transform `lub_constrain()` has an code path with a comment
```cpp
// Prevent x from reaching zero unless it really really should.
```
The limiting value `1e-15` chosen is so large as to make the transform non-monotone. The branch also cannot prevent rounding when the lower bound is not zero. e.g. `<lower=100,upper=101>` does not see any effect, other than it stopping derivative propagation.
Similar code is _not_ present in `lb_constrain()` which is allowed to round to the boundary value.

A related question is what to do about the unconstraining transform `lub_free()`. The `check_bounded()` is inclusive so values at boundaries are accepted but the logit function maps boundary to infinity so it will fail later. A reasonable choice might be to map the boundary values to some finite number beyond the rounding limit. However, the rounding limit depends on the bounds in a complex fashion.

#### Current Version:
v3.0.0

### PR DESCRIPTION
**Pull request by pgree**
## Summary

Fixed a discontinuity in `lub_constrain`
Generalized the `lp` template parameters in `{lub,lb,ub,identity}_constrain`

## Tests

Added test of boundary conditions in `lub_transform_test.cpp`

## Side Effects

Now lub_constrain underflows instead of having a discontinuity

## Checklist

- [x] Math issue #1441

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

File: stan/math/prim/fun/identity_constrain.hpp [hunk 1]
```diff
@@ -30,12 +30,13 @@ inline T identity_constrain(const T& x) {
...
- * @tparam T type of scalar.
+ * @tparam T type of scalar
+ * @tparam S type of log probability
  * @param[in] x scalar
  * @return transformed input
  */
-template <typename T>
-inline T identity_constrain(const T& x, T& /*lp*/) {
+template <typename T, typename S>
+inline T identity_constrain(const T& x, S& lp) {
```
Comment (mcol) [inline stan/math/prim/fun/identity_constrain.hpp]: This should still be `/*lp*/` as the `lp` variable is unused in the function body and it may produce a warning.

File: stan/math/prim/fun/lub_constrain.hpp [hunk 2]
```diff
@@ -130,18 +114,10 @@ inline return_type_t<T, L, U> lub_constrain(const T& x, const L& lb,
...
   } else {
     T exp_x = exp(x);
     inv_logit_x = inv_logit(x);
     lp += log(ub - lb) + x - 2 * log1p(exp_x);
-    // Prevent x from reaching zero unless it really really should.
-    if (x > NEGATIVE_INFTY && inv_logit_x == 0) {
-      inv_logit_x = 1e-15;
-    }
   }
   return fma(ub - lb, inv_logit_x, lb);
```
Comment (mcol) [inline stan/math/prim/fun/lub_constrain.hpp]: I know this is preexisting, but the computation of `inv_logit(x)` could be done in just one place (such as in the return line) rather that in both branches of the `if`.

File: stan/math/prim/fun/identity_constrain.hpp (hunk 1 above)
Comment (mcol) [reply stan/math/prim/fun/identity_constrain.hpp]: We already have a version without the `lp` argument. This other one is for symmetry with the other constraint functions which have that argument and pass it to `identity_constraint`, even if it's not used. I don't feel I understand this stuff well enough to depart from the existing signatures.

Comment (charlesm93) [reply stan/math/prim/fun/identity_constrain.hpp]: Ok. I don't think symmetry alone is a good enough reason to keep a piece of code. @bob-carpenter, I think you understand this better than I do -- is there any good reason for overloading `identity_constraint` here?

Comment (bob-carpenter) [reply stan/math/prim/fun/identity_constrain.hpp]: > This should still be /*lp*/ as the lp variable is unused in the function body

If the types get relaxed, we need it for type inference.  That's done statically, so there's no runtime overhead.

> I don't feel I understand this stuff well enough to depart from the existing signatures.

I built the constrain/unconstrain idiom for doing this when we first built the language.  That was very early on in my understanding of C++ and we were having a lot of trouble getting the simplest things to compile.

The current change strictly generalizes the set of instantiations allowed.  In Stan as currently deployed, all arguments will be at least type `double`.  

> is there any good reason for overloading identity_constraint here?

The goal is to relax the type instantiations here to allow for `int` arguments to constraints with `double` or `var` or `fvar` arguments to `lp`.  That will come up if these ever get exposed to the language, as we've been proposing to do forever. 

As is, we can't write tests with `int` arguments along with `double` arguments for `lp`.  

I opened issue https://github.com/stan-dev/math/issues/1733 to request a universal fix.

Whoever's reviewing this needs to decide if it's OK to have a partial solution.  I've been of a fix-it-as-you-go mindset with this kind of stuff, but I can see the argument for consistency across constraints and it's up to whoever is reviewing to decide.

Thanks for looking at this so closely, by the way!

File: stan/math/prim/fun/lub_constrain.hpp (hunk 2 above)
Comment (bob-carpenter) [reply stan/math/prim/fun/lub_constrain.hpp]: It needs to be pulled up above the conditional because the value is used in the condition.

**Comment by bob-carpenter** [comment]
There were no replies to my earlier comments, so I suggested to @pgree that he could finish this by:

1. cleaning up the duplicated `inv_logit` call, and

2. leaving the generalized signatures with arguments that are now needed for type inference.

If that's not OK, could you please clarify what you are requesting to change, @charlesm93?

**Comment by charlesm93** [comment]
@bob-carpenter just coming back from a trip, will respond to your comments tomorrow morning.

File: stan/math/prim/fun/identity_constrain.hpp (hunk 1 above)
Comment (charlesm93) [reply stan/math/prim/fun/identity_constrain.hpp]: I'm ok with the the fix-it-as-you-go approach, especially since this PR is straightforward and we have an issue for the universal fix.

File: stan/math/prim/fun/lub_constrain.hpp (hunk 2 above)
Comment (charlesm93) [reply stan/math/prim/fun/lub_constrain.hpp]: Ok if we implement @bob-carpenter 's suggestion.

**Comment by pgree** [comment]
@charlesm93 made the requested changes, ready for review

**Comment by charlesm93** [comment]
Looks good to me. If the continuous integration passes, we can merge.

**Comment by charlesm93** [comment]
@pgree, I'll leave you the honor to press the "merge pull request" button. Welcome to the dev team!

**Comment by bob-carpenter** [comment]
I don't think he has permission to merge yet.

> @pgree, I'll leave you the honor to press the "merge pull request" button.
