### PR TITLE
Switched ode solvers and algebra solvers to use domain_errors

### LINKED ISSUE #1887: Errors thrown from ODE solvers are runtime errors. They should probably be domain_errors
## Description

The Boost RK45 max_step_checker throws runtime errors: https://www.boost.org/doc/libs/1_73_0/libs/numeric/odeint/doc/html/boost/numeric/odeint/max_step_checker.html

The CVODES solvers throw runtime errors: https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_flag_sundials.hpp

Can we change these to domain errors? We'd change the boost one by just reimplementing our own max_step_checker (which would be relatively easy).

The reason I am asking is because right now if you accidentally get a bad initialization on your ODE, the runtime errors will make Stan give up and not try different initial conditions and you get an error like:
```
Unrecoverable error evaluating the log probability at the initial value.
Exception: Max number of iterations exceeded (500). (in 'lv3.stan', line 18, column 4 to column 28)
Exception: Max number of iterations exceeded (500). (in 'lv3.stan', line 18, column 4 to column 28)
```

In reality all that is happened is you've fed a crazy initial condition into the ODE solver and it gave up the solve, and you should just try another one. Same as if you get NaNs or something in another situation.

The logic for this is in here: https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/initialize.hpp#L111 . With domain errors we retry, and with runtime errors (or any other kind of error), we just bail.

I don't think we necessarily want to start ignoring runtime errors in that initialization. Most of those are probably index out of bounds and stuff that should blow up (hence I made this issue in Math).

#### Current Version:
v3.2.0

### PR DESCRIPTION
**Pull request by bbbales2**
When hitting numeric problems, we want to throw domain_errors instead of runtime_errors cause runtime_errors will stop the chain but domain_errors will allow the chain to retry at different parameters.

This can cause problems at initialization.

I made the changes for the ode solvers and the algebra solvers (even though the issue was just for the ode solvers).

Closes #1887.

## Checklist

- [x] Math issue #1887 

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

File: stan/math/prim/functor/integrate_ode_rk45.hpp [hunk 1]
```diff
@@ -120,26 +121,34 @@ std::vector<std::vector<return_type_t<T1, T2, T_t0, T_ts>>> integrate_ode_rk45(
...
-      max_step_checker(max_num_steps));
+  try {
+    integrate_times(
+        make_dense_output(absolute_tolerance, relative_tolerance,
+                          runge_kutta_dopri5<std::vector<double>, double,
+                                             std::vector<double>, double>()),
+        std::ref(coupled_system), initial_coupled_state, std::begin(ts_vec),
+        std::end(ts_vec), step_size, filtered_observer,
+        max_step_checker(max_num_steps));
+  } catch (no_progress_error& e) {
```
Comment (bob-carpenter) [inline stan/math/prim/functor/integrate_ode_rk45.hpp:147]: Shouldn't this be const?  No namespace?

File: stan/math/prim/functor/integrate_ode_rk45.hpp [hunk 2]
```diff
@@ -120,26 +121,34 @@ std::vector<std::vector<return_type_t<T1, T2, T_t0, T_ts>>> integrate_ode_rk45(
...
   // conventions of odeint in the output
+  size_t timestep = 0;
   auto filtered_observer
       = [&](const std::vector<double>& coupled_state, double t) -> void {
     if (!observer_initial_recorded) {
       observer_initial_recorded = true;
       return;
     }
     observer(coupled_state, t);
+    timestep++;
```
Comment (bob-carpenter) [inline stan/math/prim/functor/integrate_ode_rk45.hpp:132]: This looks like it's going beyond just changing error type.  Can you explain what these modifications are intended to do in the PR?

File: stan/math/prim/functor/integrate_ode_rk45.hpp [hunk 3]
```diff
@@ -120,26 +121,34 @@ std::vector<std::vector<return_type_t<T1, T2, T_t0, T_ts>>> integrate_ode_rk45(
...
+  try {
+    integrate_times(
+        make_dense_output(absolute_tolerance, relative_tolerance,
+                          runge_kutta_dopri5<std::vector<double>, double,
+                                             std::vector<double>, double>()),
+        std::ref(coupled_system), initial_coupled_state, std::begin(ts_vec),
+        std::end(ts_vec), step_size, filtered_observer,
+        max_step_checker(max_num_steps));
+  } catch (no_progress_error& e) {
+    throw_domain_error("integrate_ode_rk45", "", ts_vec[timestep + 1],
```
Comment (bob-carpenter) [inline stan/math/prim/functor/integrate_ode_rk45.hpp:148]: Why a mix of explicit calls to `throw` and this `throw_domain_error` helper?

File: stan/math/rev/functor/cvodes_integrator.hpp [hunk 4]
```diff
@@ -81,7 +81,13 @@ class cvodes_integrator {
...
     using param_var = stan::is_var<T_param>;
 
-    const char* fun = "integrate_ode_cvodes";
+    const char* fun;
+
+    if (Lmm == CV_BDF) {
+      fun = "integrate_ode_bdf";
+    } else {
+      fun = "integrate_ode_adams";
+    }
```
Comment (bob-carpenter) [inline stan/math/rev/functor/cvodes_integrator.hpp:90]: This should be a one-liner:

```
const char* fun = Lmm == CV_BDF ? "integrate_ode_bdf" : "integrate_ode_adams";
```

File: stan/math/rev/functor/cvodes_integrator.hpp [hunk 5]
```diff
@@ -165,9 +171,14 @@ class cvodes_integrator {
       for (size_t n = 0; n < ts.size(); ++n) {
         double t_final = ts_dbl[n];
         if (t_final != t_init) {
-          check_flag_sundials(CVode(cvodes_mem, t_final, cvodes_data.nv_state_,
-                                    &t_init, CV_NORMAL),
-                              "CVode");
+          int ret = CVode(cvodes_mem, t_final, cvodes_data.nv_state_, &t_init,
+                          CV_NORMAL);
+
+          if (ret == CV_TOO_MUCH_WORK) {
```
Comment (bob-carpenter) [inline stan/math/rev/functor/cvodes_integrator.hpp:177]: This is great---it'll produce much better output.

File: stan/math/prim/functor/integrate_ode_rk45.hpp (hunk 3 above)
Comment (bbbales2) [reply stan/math/prim/functor/integrate_ode_rk45.hpp:148]: It appears most of this code was written with throw instead of using the internal error functions.

Where I added new errors I used the internal error functions. Didn't want to do the code cleanup everywhere.

Comment (bbbales2) [reply stan/math/prim/functor/integrate_ode_rk45.hpp:148]: Change "most" to "some"

File: stan/math/prim/functor/integrate_ode_rk45.hpp (hunk 2 above)
Comment (bbbales2) [reply stan/math/prim/functor/integrate_ode_rk45.hpp:132]: This is so the error can be informative about where the ODE solve broke. It can print out 'failed to integrate to time 7.5' for instance, instead of saying 'failed to integrate hit max_num_steps'. It just seemed more informative.

File: stan/math/rev/functor/cvodes_integrator.hpp (hunk 4 above)
Comment (bbbales2) [reply stan/math/rev/functor/cvodes_integrator.hpp:90]: This should be an argument to the function haha

**Comment by bbbales2** [comment]
@bob-carpenter tests passed, ready for review

**Comment by bbbales2** [comment]
@bob-carpenter tests pass this is ready for review again.

File: stan/math/rev/functor/cvodes_integrator.hpp (hunk 4 above)
Comment (bbbales2) [reply stan/math/rev/functor/cvodes_integrator.hpp]: I made this an argument to the function.

File: stan/math/prim/functor/integrate_ode_rk45.hpp (hunk 3 above)
Comment (bbbales2) [reply stan/math/prim/functor/integrate_ode_rk45.hpp:148]: I changed a couple of the manual throws to `throw_domain_errors`. I kindof abused the syntax to get a reasonable error message, but they're tested so if the formatting changes someone will at least have to look at them.

**Comment by bbbales2** [comment]
This is ready for review.

File: stan/math/prim/err/check_flag_sundials.hpp [hunk 6]
```diff
@@ -28,9 +29,8 @@ inline void check_flag_kinsol(int flag,
                               long int max_num_steps) {  // NOLINT(runtime/int)
   std::ostringstream ss;
   if (flag == -6) {
-    ss << "algebra_solver: max number of iterations: " << max_num_steps
```
Comment (rok-cesnovar) [inline stan/math/prim/err/check_flag_sundials.hpp:31]: Both files in this file don't have complete doxygen (param and throw are missing). Mind fixing both here? The check_flag_kinsol should be fixed as its being modified.

File: stan/math/rev/functor/cvodes_integrator.hpp [hunk 7]
```diff
@@ -72,7 +73,8 @@ class cvodes_integrator {
   template <typename F, typename T_initial, typename T_param, typename T_t0,
```
Comment (rok-cesnovar) [inline stan/math/rev/functor/cvodes_integrator.hpp:73]: throw doxygen missing here.

**Comment by rok-cesnovar** [comment]
@bob-carpenter are you good with the changes? There is a "request changes" still active.

**Comment by bbbales2** [comment]
@bob-carpenter ping
