### PR TITLE
Don't throw when computing the inverse of a size zero matrix

### LINKED ISSUE #1432: inverse_spd should have consistent errors on size 0
## Description

This test should pass in `test/unit/math/mix/mat/fun/inverse_spd_test.cpp`:

```
Eigen::MatrixXd m00(0, 0);
stan::test::expect_ad(f, m00);
```

Edit:  I previous indicated this was an error, but I don't see why the unique 0 x 0 matrix isn't considered the inverse of the 0 x 0 matrix.  It satisfies the identity laws.  Also, I'd think that the determinant of an empty matrix would be one as it's a product, and the empty product is one.

#### Current Version:
v3.0.0

### LINKED ISSUE #1463: inverse should have consistent errors on size 0 inputs
## Description
There's a test that's currently commented out in test/unit/math/mix/mat/fun/inverse_test.cpp because it fails, due to inconsistent behaviour of `inverse` on size 0 inputs between prim and rev.

That test could be replaced with the following, which is more general:

```
Eigen::MatrixXd t2(0, 0);
stan::test::expect_ad(f, t2);
```

It will work after making prim throw on size 0 inputs.

### PR DESCRIPTION
**Pull request by mcol**
## Summary
This reverts the earlier decision to throw when computing the inverse of a size zero matrix, as discussed in #1689. We need to return an empty matrix ourselves because Eigen asserts when computing the inverse of an empty matrix. Fixes #1463. Fixes #1432.

## Tests

Updated accordingly. There were also a couple of errors in those tests concerning the type of exception thrown.

## Side Effects

None.

## Checklist

- [X] Math issue #1463, #1432

- [X] Copyright holder: Marco Colombo

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

File: stan/math/rev/fun/inverse.hpp [hunk 1]
```diff
@@ -70,12 +70,17 @@ class inverse_vari : public vari {
...
+ * @param m specified matrix
+ * @return Inverse of the matrix (an empty matrix if the specified matrix has
+ * size zero).
+ * @throw std::invalid_argument if the matrix is not square.
  */
 inline matrix_v inverse(const matrix_v &m) {
   check_square("inverse", "m", m);
-  check_nonempty("inverse", "m", m);
+  if (m.size() == 0) {
+    return matrix_v(0, 0);
```
Comment (bob-carpenter) [inline stan/math/rev/fun/inverse.hpp]: [optional]
This could be `return {0, 0};` to match the other definitions.

**Comment by bob-carpenter** [comment]
I approved because I don't think it's worth changing return style, but I'll let @mcol decide.   Feel free to merge as is.

**Comment by mcol** [comment]
Since I didn't think it was worth just that one case, I corrected that pattern everywhere.
