### PR TITLE
Fix `cholesky_decompose` not updating adjoints correct (2.26)

### LINKED ISSUE #2364: `cholesky_decompose` not propagating derivatives correctly in 2.26
## Description

This bug came up on the Stan forums: https://discourse.mc-stan.org/t/wrong-gradient-in-updated-stan-unsure-if-rstan-or-stan-problem/20673

Gradients of this test model computed in the develop rstan show problems (source: https://discourse.mc-stan.org/t/wrong-gradient-in-updated-stan-unsure-if-rstan-or-stan-problem/20673/14):
```stan
data{
  int mat_size;
  real y_mean;
} 
parameters{
  real y;
}
transformed parameters{
  matrix[mat_size,mat_size] test_mat = diag_matrix(rep_vector(y,mat_size));
  real trans_y = sum(cholesky_decompose(test_mat));
}
model{ 
  y ~ normal(y_mean,trans_y);
}
```

#### Current Version:
v4.0.0

### PR DESCRIPTION
**Pull request by bbbales2**
## Summary

Fixes #2364 . The problem was `cholesky_decompose` not updating the input adjoints correctly (but doing it in a way that it would pass generic autodiff tests).

## Tests

Added one!

## Release notes

 - Fixed issue with `cholesky_decompose` not propagating derivatives correctly

## Checklist

- [x] Math issue #2364 

- [x] Copyright holder: Columbia University

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

### CODE REVIEW

**Comment by bbbales2** [comment]
Will this test run correctly for opencl when opencl is turned on? I guess, did opencl have this problem?

**Comment by rok-cesnovar** [comment]
Based on https://github.com/stan-dev/math/blob/develop/stan/math/opencl/rev/cholesky_decompose.hpp#L72 I would say no? But I am going to push the same test to the OpenCL variant as well.

File: stan/math/rev/fun/cholesky_decompose.hpp [hunk 1]
```diff
@@ -87,7 +89,7 @@ inline auto cholesky_lambda(T1& L_A, T2& L, T3& A) {
     using Eigen::Lower;
     using Eigen::StrictlyUpper;
     using Eigen::Upper;
-    Eigen::MatrixXd L_adj(L.rows(), L.cols());
+    Eigen::MatrixXd L_adj = Eigen::MatrixXd::Zero(L.rows(), L.cols());
```
Comment (SteveBronder) [inline stan/math/rev/fun/cholesky_decompose.hpp:92]: Oh interesting, was the issue here that the upper triangular part of the matrix was not being set?

**Review by SteveBronder — APPROVED** [review]

File: stan/math/rev/fun/cholesky_decompose.hpp (hunk 1 above)
Comment (bbbales2) [reply stan/math/rev/fun/cholesky_decompose.hpp:92]: Actually I meant to leave a comment there. That one change I just did cause it looked scary and was too lazy to check the Eigen docs or carefully read the code.

Comment (bbbales2) [reply stan/math/rev/fun/cholesky_decompose.hpp:92]: That one can def. be reverted but I just saw it and got nervous.

**Comment by SteveBronder** [comment]
Looks like it failed on the upstream?

https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_hotfix/7/pipeline/

**Comment by rok-cesnovar** [comment]
Yeah, I dont get that error "You are not currently on a branch.". @serban-nicusor-toptal will know for sure :)

**Comment by serban-nicusor-toptal** [comment]
I'm on it, checking to see what's wrong.

**Comment by rok-cesnovar** [comment]
Thanks! Seems like the issue on the Stan repo was fixed but now the same one popped up in CmdStan.

**Comment by serban-nicusor-toptal** [comment]
Hey it looks all fixed now. `downstream_hotfix` was badly configured, fixed it and it shouldn't happen again.
Sorry for the inconvenience caused.

**Comment by rok-cesnovar** [comment]
@bbbales2 merge?

**Comment by bbbales2** [comment]
Can I press the button?

**Comment by wds15** [comment]
How about we align on discourse about 2.26.1 ?
