### PR TITLE
Make singular_values work with size 0 input

### LINKED ISSUE #1439: singular_values fails with size 0 input
## Description

This should pass in `test/unit/math/mix/mat/fun/singular_values_test.cpp`:

```
  Eigen::MatrixXd m00(0, 0);
  stan::test::expect_ad(f, m00);
```

It currently hits an assertion in Eigen.

#### Current Version:
v3.0.0

### PR DESCRIPTION
**Pull request by mcol**
## Summary

Fixes #1439 so that in case of size 0 input we return before getting into Eigen.

## Tests

Added test suggested in the issue.

## Side Effects

None.

## Checklist

- [X] Math issue #1439

- [X] Copyright holder: Marco Colombo

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [X] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [X] the code is written in idiomatic C++ and changes are documented in the doxygen

- [X] the new changes are tested

### CODE REVIEW

File: stan/math/prim/mat/fun/singular_values.hpp [hunk 1]
```diff
@@ -10,13 +10,16 @@ namespace math {
...
  * <p>See the documentation for <code>svd()</code> for
- * information on the signular values.
+ * information on the singular values.
  * @param m Specified matrix.
  * @return Singular values of the matrix.
  */
 template <typename T>
 Eigen::Matrix<T, Eigen::Dynamic, 1> singular_values(
     const Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>& m) {
+  if (m.rows() == 0 || m.cols() == 0)
```
Comment (rok-cesnovar) [inline stan/math/prim/mat/fun/singular_values.hpp]: We can just use `m.size() == 0` here.

Comment (mcol) [reply stan/math/prim/mat/fun/singular_values.hpp]: Thanks!

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal Is Jenkins down currently?

**Comment by serban-nicusor-toptal** [comment]
It is, I'm on it.

**Comment by rok-cesnovar** [comment]
@mcol Does test/unit/math/mix/mat/fun/add_test fail for you locally? I restarted the tests to eliminate it was a weird error on Jenkins.

**Comment by mcol** [comment]
It passes for me on Linux.

**Comment by rok-cesnovar** [comment]
It seems that @SteveBronder resolved the issue with the tests so this should be good to go. There are now a bunch of jobs waiting for Jenkins to tests and I dont want to add more so I will wait for the queue to empty a bit and then merge. 

Thanks again @mcol for all these boundary issues fixes. Sorry for the CI troubles :)
